### ISSUE TITLE
Access Process Description

### ISSUE THREAD

**Issue by hugogva** [giampaolo/psutil#1795] opened 2020-07-22 22:26 UTC
Hello,
I was wondering if there is any possible way to access a process description instead of Name/PID using this library ?

Thanks in advance for your response.

**Comment by giampaolo** [comment] 2020-07-23 00:39
Mmmm... no there isn't. I considered that but it would be Windows-only, plus I've never received a request for it so I suppose the demand/need for it would be fairly low.

**Comment by hugogva** [comment] 2020-07-23 08:27
I am highly interested to have this if possible.

I am developing a software and to avoid people using tools such as
debuggers and sniffers I am using your module to check for the names of the
debuggers inside all the processes.

The small issue is if the debugger’s name is changed then it won’t detect
it so I figured out the only solution would be to use the description since
it’s difficult to change it.

Maybe you have another idea in mind for what to check apart the description
? 😀

Looking further to your response

Hugo

Le jeu. 23 juil. 2020 à 02:39, giampaolo <notifications@github.com> a
écrit :

**Comment by giampaolo** [comment] 2020-07-23 10:29
I see (there's a use case). The other idea is mixing name(), cmdline() and exe():
https://psutil.readthedocs.io/en/latest/#find-process-by-name

**Comment by hugogva** [comment] 2020-07-23 22:47
Thanks for this proposition i just added it ! I can still see that if the folder name is changed then we still can’t detect the process name. I am really looking for Something very secure such as process description since it’s quite hard to change. I am willing to contribute to the project by paying you a bit if you would be interested to add this feature or other stuff 😊. Keep me updated. Hugo De : giampaoloEnvoyé le :jeudi, 23 juillet 2020 12:29À : giampaolo/psutilCc : hugo utz; AuthorObjet :Re: [giampaolo/psutil] Access Process Description (#1795) I see (there's a use case). The other idea is mixing name(), cmdline() and exe():https://psutil.readthedocs.io/en/latest/#find-process-by-name—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by giampaolo** [comment] 2020-10-17 12:05
Closing as duplicate of #1113.

**Closed by giampaolo** 2020-10-17 12:05 UTC
