### ISSUE TITLE
MacOS 10.12 Install fails: 'float.h' file not found

### ISSUE THREAD

**Issue by malcolmsailor** [giampaolo/psutil#1256] opened 2018-03-28 11:58 UTC
Hello,

I am getting the following installation error when attempting to install psutil with pip on macOS 10.12.6.

```
    In file included from psutil/_psutil_osx.c:36:
    In file included from /Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/include/float.h:36:
    /Developer/SDKs/MacOSX10.6.sdk/usr/include/float.h:8:15: fatal error: 'float.h' file not found
    #include_next <float.h>
                  ^~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
```

As best I can tell, both float.h files that are found have `#include_next <float.h>` statements, and after this it cannot find the file in the search path.

This issue is a little over my head. I can easily imagine that the problem with my machine more generally and not a problem with psutil specifically, but I have not previously come across this error before and have been unable to find anything about similar issues online. Any help would be very much appreciated!

**Comment by osuskates** [comment] 2018-04-04 11:30
I am also experiencing this exact same error message. Is there a fix or workaround available?

**Comment by nstr10** [comment] 2018-04-05 16:00
`float.h` is included in gcc, so it sounds like a `PATH` problem to me. Try `locate float.h` and ensure that its path is part of your `PATH` environment variable.

**Comment by osuskates** [comment] 2018-04-06 12:46
@nstr10, thanks for the suggestion, however, after adding the full path to float.h, it was still failing with the same error message that @malcolmsailor was getting. Might you have any other suggestions?

**Comment by nstr10** [comment] 2018-04-06 14:49
@osuskates unfortunately I'm not able to reproduce this - did a `brew install python3 && pip3 install psutil` and it installed without issue. :confused:

Only obvious difference is that I'm still on El Capitan (10.11.2).

**Comment by rorycurtis** [comment] 2018-05-14 11:03
I had exactly the same issue with another package and supplying the correct include directory solved it, like this ...

`CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include pip3 install ...`

You can find the right path to use by running

`xcrun --show-sdk-path`

**Comment by giampaolo** [comment] 2020-12-19 14:51
Python wheels are now distributed for macOS so this should not be a problem anymore. Closing.

**Closed by giampaolo** 2020-12-19 14:51 UTC
Labels: bug, macos
