### ISSUE TITLE
[Ubuntu 17.04 VM] cpu_count test error

### ISSUE THREAD

**Issue by davidbrochart** [giampaolo/psutil#1499] opened 2019-04-26 08:07 UTC
**Platform**
* Ubuntu 17.04 (VMware virtual machine on a Windows host)
* 5.6.2
**Bug description**
[This test](https://github.com/giampaolo/psutil/blob/c78a850358af883dcaa63a3f9204f15cc129e518/psutil/tests/test_linux.py#L678-L686) fails because `cpu_count(logical=False)` returns `1`, and `lscpu -p` returns:
```
# The following is the parsable format, which can be fed to other
# programs. Each different item in every column has an unique ID
# starting from zero.
# CPU,Core,Socket,Node,,L1d,L1i,L2,L3
0,0,0,0,,0,0,0,0
1,1,1,0,,1,1,1,1
2,2,2,0,,2,2,2,2
3,3,3,0,,3,3,3,3
```

**Test results**
```
_______________________________________________________________________________________________ TestSystemCPUCountPhysical.test_against_lscpu _______________________________________________________________________________________________

self = <psutil.tests.test_linux.TestSystemCPUCountPhysical testMethod=test_against_lscpu>

    @unittest.skipIf(not which("lscpu"), "lscpu utility not available")
    def test_against_lscpu(self):
        out = sh("lscpu -p")
        core_ids = set()
        for line in out.split('\n'):
            if not line.startswith('#'):
                fields = line.split(',')
                core_ids.add(fields[1])
>       self.assertEqual(psutil.cpu_count(logical=False), len(core_ids))
E       AssertionError: 1 != 4

test_linux.py:686: AssertionError
```

**Comment by giampaolo** [comment] 2020-12-29 00:48
It's likely this is a duplicate of #1620 which was fixed in 5.7.3. Closing.

**Closed by giampaolo** 2020-12-29 00:48 UTC
Labels: bug, linux, tests
