### ISSUE TITLE
psutils issue

### ISSUE THREAD

**Issue by jyotihirak11** [giampaolo/psutil#1706] opened 2020-02-24 13:14 UTC
**Platform**
*  Windows 10
* { psutil version: python3 -c "import psutil; print(psutil.__version__)" } pip install target-stitch
* { python version } python 3.8.1

**Bug description**
Can anyone help. I am facing an issue while installing target-stitch. A package called psutils is showing an error while installing# Running setup.py install for psutil ... error. Also one more error is there # error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2
Here is the code

**Test results**
```
C:\Users\Admin>pip install target-stitch                                                                                               

Collecting target-stitch                                                                                                                 
Using cached target-stitch-3.0.2.tar.gz (10.0 kB)                                                                                    

Requirement already satisfied: jsonschema==2.6.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from target-stitch) (2.6.0)                                                                                                                      


Requirement already satisfied: mock==2.0.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from target-stitch) (2.0.0)                                                                                                                            


Requirement already satisfied: requests==2.20.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from target-stitch) (2.20.0)                                                                                                                     
 

Requirement already satisfied: singer-python==5.8.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from target-stitch) (5.8.0)                                                                                                                   


Collecting psutil==5.3.1                                                                                                                
 
Using cached psutil-5.3.1.tar.gz (397 kB)                                                                                            

Requirement already satisfied: simplejson==3.11.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from target-stitch) (3.11.1)                                                                                                                    


Processing c:\users\admin\appdata\local\pip\cache\wheels\89\84\e6\de199bc435ee4eb6a0d978d3b59457fd05ac67ab1bc4e66e11\aiohttp-3.5.4-py3-none-any.whl                                                                                                                           



Collecting cchardet==2.1.4                                                                                                               

Using cached cchardet-2.1.4.tar.gz (648 kB)                                                                                          

Collecting aiodns==2.0.0                                                                                                               
  
Using cached aiodns-2.0.0-py2.py3-none-any.whl (4.8 kB)                                                                              

Requirement already satisfied: ciso8601 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from target-stitch) (2.1.3)                                                                                                                             
  
Requirement already satisfied: six>=1.9 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from mock==2.0.0->target-stitch) (1.14.0)                                                                                                                 

Requirement already satisfied: pbr>=0.11 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from mock==2.0.0->target-stitch) (5.4.4)                                                                                                                 

Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from requests==2.20.0->target-stitch) (2019.11.28)                                                                                             
 
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from requests==2.20.0->target-stitch) (1.24.3)                                                                                             
 
 Requirement already satisfied: idna<2.8,>=2.5 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from requests==2.20.0->target-stitch) (2.7)                                                                                                      
  
 Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from requests==2.20.0->target-stitch) (3.0.4)                                                                                             
  
 Requirement already satisfied: pytz==2018.4 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from singer-python==5.8.0->target-stitch) (2018.4)                                                                                                    

Requirement already satisfied: python-dateutil>=2.6.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from singer-python==5.8.0->target-stitch) (2.8.1)                                                                                           

Requirement already satisfied: backoff==1.8.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from singer-python==5.8.0->target-stitch) (1.8.0)                                                                                                   

Collecting async-timeout<4.0,>=3.0                                                                                                       

Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)                                                                           

Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from aiohttp==3.5.4->target-stitch) (19.3.0)                                                                                                        

 Collecting multidict<5.0,>=4.0                                                                                                           

Using cached multidict-4.7.5-cp38-cp38-win_amd64.whl (48 kB)                                                                         

Collecting yarl<2.0,>=1.0                                                                                                               
 Using cached yarl-1.4.2-cp38-cp38-win_amd64.whl (126 kB)                                                                             

Collecting pycares>=3.0.0                                                                                                                Using cached pycares-3.1.1-cp38-cp38-win_amd64.whl (70 kB)                                                                           

Requirement already satisfied: cffi>=1.5.0 in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from pycares>=3.0.0->aiodns==2.0.0->target-stitch) (1.14.0)                                                                                            

Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python38\lib\site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns==2.0.0->target-stitch) (2.19)                                                                                   

Installing collected packages: psutil, async-timeout, multidict, yarl, aiohttp, cchardet, pycares, aiodns, target-stitch                
 Attempting uninstall: psutil                                                                                                             Found existing installation: psutil 5.7.0                                                                                              Uninstalling psutil-5.7.0:                                                                                                               Successfully uninstalled psutil-5.7.0                                                                                                

Running setup.py install for psutil ... error                                                                                          

ERROR: Command errored out with exit status 1:                                                                                          

command: 'c:\users\admin\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-1uuphvqa\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-1uuphvqa\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-e9xburhp\install-record.txt' --single-version-externally-managed --compile --install-headers 



'c:\users\admin\appdata\local\programs\python\python38\Include\psutil'                                                                                                            

cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-1uuphvqa\psutil\                                                               

Complete output (56 lines):                                                                                                            running install                                                                                                                        
running build                                                                                                                        
  running build_py                                                                                                                      
 creating build                                                                                                                       
  
creating build\lib.win-amd64-3.8                                                                                                       

creating build\lib.win-amd64-3.8\psutil                                                                                                

copying psutil\_common.py -> build\lib.win-amd64-3.8\psutil                                                                            

copying psutil\_compat.py -> build\lib.win-amd64-3.8\psutil                                                                            

copying psutil\_psbsd.py -> build\lib.win-amd64-3.8\psutil                                                                             

copying psutil\_pslinux.py -> build\lib.win-amd64-3.8\psutil                                                                           

copying psutil\_psosx.py -> build\lib.win-amd64-3.8\psutil                                                                             

copying psutil\_psposix.py -> build\lib.win-amd64-3.8\psutil                                                                           

copying psutil\_pssunos.py -> build\lib.win-amd64-3.8\psutil                                                                           

copying psutil\_pswindows.py -> build\lib.win-amd64-3.8\psutil                                                                         

copying psutil\__init__.py -> build\lib.win-amd64-3.8\psutil                                                                           

creating build\lib.win-amd64-3.8\psutil\tests                                                                                          

copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.8\psutil\tests                                                               

copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.8\psutil\tests                                                       

copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.8\psutil\tests                                                         

copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.8\psutil\tests                                                             

copying psutil\tests\test_memory_leaks.py -> build\lib.win-amd64-3.8\psutil\tests                                                      

copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.8\psutil\tests                                                              

copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.8\psutil\tests                                                               

copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.8\psutil\tests                                                             

copying psutil\tests\test_process.py -> build\lib.win-amd64-3.8\psutil\tests                                                           

copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.8\psutil\tests                                                             

copying psutil\tests\test_system.py -> build\lib.win-amd64-3.8\psutil\tests                                                            

copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.8\psutil\tests                                                           

copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.8\psutil\tests                                                           

copying psutil\tests\__init__.py -> build\lib.win-amd64-3.8\psutil\tests                                                               

copying psutil\tests\__main__.py -> build\lib.win-amd64-3.8\psutil\tests                                                               

running build_ext                                                                                                                     

 building 'psutil._psutil_windows' extension                                                                                            b'\\\x00C\x00o\x00m\x00m\x00o\x00n\x00 \x00w\x00a\x00s\x00 \x00u\x00n\x00e\x00x\x00p\x00e\x00c\x00t\x00e\x00d\x00 \x00a\x00t\x00 \x00t\x00h\x00i\x00s\x00 \x00t\x00i\x00m\x00e\x00.\x00\r\x00\n\x00'                                                                          


creating build\temp.win-amd64-3.8                                                                                                      creating build\temp.win-amd64-3.8\Release                                                                                              creating build\temp.win-amd64-3.8\Release\psutil                                                                                       creating build\temp.win-amd64-3.8\Release\psutil\arch                                                                                  creating build\temp.win-amd64-3.8\Release\psutil\arch\windows                                                                          




C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPSUTIL_WINDOWS=1 -DPSUTIL_VERSION=531 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -
Ic:\users\admin\appdata\local\programs\python\python38\include -Ic:\users\admin\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" 

"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\include\um" /Tcpsutil/_psutil_common.c /Fobuild\temp.win-amd64-3.8\Release\psutil/_psutil_common.obj     _
psutil_common.c                                                                                                                       


C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPSUTIL_WINDOWS=1 -DPSUTIL_VERSION=531 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -Ic:\users\admin\appdata\local\programs\python\python38\include -Ic:\users\admin\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\include\um" /Tcpsutil/_psutil_windows.c /Fobuild\temp.win-amd64-3.8\Release\psutil/_psutil_windows.obj                                                                                                                                          _psutil_windows.c                                                                                                                      

C:\Users\Admin\AppData\Local\Temp\pip-install-1uuphvqa\psutil\psutil\arch\windows\ntextapi.h(166): error C2011: '_CLIENT_ID': 'struct' type redefinition                                                                                                                    
 
 C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winternl.h(80): note: see declaration of '_CLIENT_ID'                   

C:\Users\Admin\AppData\Local\Temp\pip-install-1uuphvqa\psutil\psutil\arch\windows\ntextapi.h(172): 
error C2011: '_SYSTEM_THREAD_INFORMATION': 'struct' type redefinition                                                                                                      


C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winternl.h(286): note: see declaration of '_SYSTEM_THREAD_INFORMATION'                                                                                                                                         

C:\Users\Admin\AppData\Local\Temp\pip-install-1uuphvqa\psutil\psutil\arch/windows/inet_ntop.h(15): warning C4028: formal parameter 2 different from declaration                                                                                                               

psutil/_psutil_windows.c(839): warning C4267: '=': conversion from 'size_t' to 'DWORD', possible loss of data                        
  
psutil/_psutil_windows.c(2078): warning C4312: 'type cast': conversion from 'int' to 'PVOID' of greater size                         
  
psutil/_psutil_windows.c(2769): error C2039: 'ContextSwitches': is not a member of '_SYSTEM_THREAD_INFORMATION'                      
  
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winternl.h(286): note: see declaration of '_SYSTEM_THREAD_INFORMATION'                                                                                                                                         

psutil/_psutil_windows.c(2888): warning C4133: 'function': incompatible types - from 'MEMORY_BASIC_INFORMATION64 *' to 'PMEMORY_BASIC_INFORMATION'                                                                                                                            psutil/_psutil_windows.c(2921): warning C4047: '=': 'PVOID' differs in levels of indirection from 'ULONGLONG'                          

psutil/_psutil_windows.c(3453): warning C4267: 'function': conversion from 'size_t' to 'ULONG', possible loss of data                 

 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2                                                                                                    
    ----------------------------------------                                                                                             

Rolling back uninstall of psutil                                                                                                       Moving to c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\psutil-5.7.0.dist-info\                             
  from C:\Users\Admin\AppData\Local\Programs\Python\Python38\Lib\site-packages\~sutil-5.7.0.dist-info                                  
 Moving to c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\psutil\                                               from C:\Users\Admin\AppData\Local\Programs\Python\Python38\Lib\site-packages\~sutil                                                 

ERROR: Command errored out with exit status 1: 'c:\users\admin\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-1uuphvqa\\psutil\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-1uuphvqa\\psutil\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-e9xburhp\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\admin\appdata\local\programs\python\python38\Include\psutil' Check the logs for full command output.
```

**Comment by fbeauche** [comment] 2020-08-07 19:43
I think it would simply require target-stich to update psutils dependencies : 
https://github.com/singer-io/target-stitch/issues/93

**Comment by giampaolo** [comment] 2020-12-19 12:19
Closing out as "not a bug"

**Closed by giampaolo** 2020-12-19 12:19 UTC
Labels: bug
