### ISSUE TITLE
cpu_percent return a bunch o 0s

### ISSUE THREAD

**Issue by KaduUlson** [giampaolo/psutil#1378] opened 2018-12-10 15:50 UTC
I'm running a python script in Red Hat 7.3.1-5 to log the Memory and CPU usage for each second. 

```
import datetime
import psutil
import pandas as pd

def writeusage(delt) :
    i = 1 
    usageLog = []
    for i in range(delt):
        usageNow = {"Time" : datetime.datetime.now(),
                    "CPU" : psutil.cpu_percent(interval = 1),
                    "MEMu": psutil.virtual_memory().used / (1024.0 ** 3),       
                    "MEMt": psutil.virtual_memory().total / (1024.0 ** 3),       
                    }
        usageLog.append(usageNow)
    return usageLog

dfusage = pd.DataFrame(writeusage(60))
```

But it returns a lot of 0s for the cpu_percent.
Is that a expected behavior?

```
    CPU            ...                                   Time
0   0.0            ...             2018-12-10 13:15:18.510315
1   0.0            ...             2018-12-10 13:15:19.512034
2   0.0            ...             2018-12-10 13:15:20.513665
3   0.0            ...             2018-12-10 13:15:21.514604
4   0.0            ...             2018-12-10 13:15:22.516246
5   0.0            ...             2018-12-10 13:15:23.517942
6   0.0            ...             2018-12-10 13:15:24.519579
7   0.0            ...             2018-12-10 13:15:25.521220
8   0.0            ...             2018-12-10 13:15:26.522852
9   0.0            ...             2018-12-10 13:15:27.524489
10  0.0            ...             2018-12-10 13:15:28.526169
11  0.0            ...             2018-12-10 13:15:29.527820
12  0.0            ...             2018-12-10 13:15:30.529541
13  0.0            ...             2018-12-10 13:15:31.531167
14  0.0            ...             2018-12-10 13:15:32.532778
15  1.0            ...             2018-12-10 13:15:33.534429
16  0.0            ...             2018-12-10 13:15:34.536053
17  0.0            ...             2018-12-10 13:15:35.537690
18  0.0            ...             2018-12-10 13:15:36.539335
```

Thanks in advance.

**Comment by giampaolo** [comment] 2018-12-13 15:56
Mmmm I cannot reproduce that.

**Comment by bshen-telesign** [comment] 2018-12-13 22:23
This is happening in python3.6 on CentOS 6.9 for me as well. The same code above reproduces it on my machine.

**Comment by Sygyzmundovych** [comment] 2018-12-15 16:06
I see similar behaviour on MacOS:
```
$ uname -a
Darwin IMAC204-08.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

I just downloaded the psutil
```
$ pip3 show psutil
Name: psutil
Version: 5.4.8
...
```

And running similar code like above (with `psutil.cpu_percent(percpu=False, interval = 1)`) gives me
```
$ python3 test_psutils.py 
{'Time': datetime.datetime(2018, 12, 15, 17, 1, 14, 684237), 'CPU': 0.0, 'MEMu': 2.9694976806640625, 'MEMt': 16.0}
{'Time': datetime.datetime(2018, 12, 15, 17, 1, 15, 694551), 'CPU': 0.0, 'MEMu': 2.969482421875, 'MEMt': 16.0}
{'Time': datetime.datetime(2018, 12, 15, 17, 1, 16, 701261), 'CPU': 0.5, 'MEMu': 2.9694747924804688, 'MEMt': 16.0}
{'Time': datetime.datetime(2018, 12, 15, 17, 1, 17, 701983), 'CPU': 0.2, 'MEMu': 2.9694595336914062, 'MEMt': 16.0}
{'Time': datetime.datetime(2018, 12, 15, 17, 1, 18, 702703), 'CPU': 0.2, 'MEMu': 2.969207763671875, 'MEMt': 16.0}
{'Time': datetime.datetime(2018, 12, 15, 17, 1, 19, 703395), 'CPU': 0.0, 'MEMu': 2.969127655029297, 'MEMt': 16.0}
```
but I am running some workload and `top` shows me CPU around `CPU usage: 5.62% user, 3.91% sys, 90.46% idle`

**Comment by Sygyzmundovych** [comment] 2018-12-15 16:13
Try adding `percpu=False` like `psutil.cpu_percent(percpu=False, interval = 1)`

**Comment by giampaolo** [comment] 2019-02-26 00:21
I'm gonna close this out as outdated. If the problem still occurs please paste the output below and we can reopen

```
import psutil, time
print(psutil.cpu_times())
stop_at = time.time() + 1
while time.time() < stop_at:
    psutil.cpu_times()
print(psutil.cpu_times())
```

**Closed by giampaolo** 2019-02-26 00:21 UTC
