### ISSUE TITLE
[AMD Linux] No such file or directory: '/proc/3790/fd/3'

### ISSUE THREAD

**Issue by chfw** [giampaolo/psutil#1617] opened 2019-11-07 23:52 UTC
**Platform**
* Ubuntu 16.04.6 LTS
* 5.6.5
* pypy 2.7

**Bug description**

Failed to read link path. And you can reproduce it with the following unit test script:

https://github.com/pyexcel/pyexcel/blob/dev/tests/test_bug_fixes.py#L243

```
git clone https://github.com/pyexcel/pyexcel
cd pyexcel
pip install -r requirements.txt -r tests/requirements.txt
nosettests tests/test_bug_fixes.py
```

And 5.6.3 works without problem. 

** Alternative way of bug reproduction **

You can choose to fork pyexcel and trigger the builds on your fork. and you can tweek psutil versions and test the builds.

```
traceback message (if any)
```

```python
code to reproduce the problem (if any)
  File "/home/travis/virtualenv/pypy2.7-6.0.0/site-packages/psutil/__init__.py", line 1255, in open_files
572    return self._proc.open_files()
573  File "/home/travis/virtualenv/pypy2.7-6.0.0/site-packages/psutil/_pslinux.py", line 1517, in wrapper
574    return fun(self, *args, **kwargs)
575  File "/home/travis/virtualenv/pypy2.7-6.0.0/site-packages/psutil/_pslinux.py", line 2030, in open_files
576    path = readlink(file)
577  File "/home/travis/virtualenv/pypy2.7-6.0.0/site-packages/psutil/_pslinux.py", line 221, in readlink
578    path = os.readlink(path)
579OSError: [Errno 2] No such file or directory: '/proc/3790/fd/3'
```

**Test results**
```
I am sorry that I could help with unit tests
output of `python -c psutil.tests` (failures only, not full result)
```
{ you may want to do this in order to discover other issues affecting your platform }
{ if failures look unrelated with the issue at hand open another ticket }

More details on failed:
https://travis-ci.org/pyexcel/pyexcel/jobs/608999052

The same build passed with psutil version is 5.6.3:
https://travis-ci.org/pyexcel/pyexcel/jobs/600983900

**Comment by giampaolo** [comment] 2020-01-10 21:55
Closing as duplicate of #1659.

**Comment by giampaolo** [comment] 2020-01-10 21:55
.

**Closed by giampaolo** 2020-01-10 21:55 UTC
Labels: bug
