### ISSUE TITLE
[Windows] psutil 5.8.0 segfaults on disk_partitions()

### ISSUE THREAD

**Issue by Huite** [giampaolo/psutil#2038] opened 2021-12-23 15:56 UTC
## Summary

* OS: Windows
* Architecture: 64bit
* Psutil version: 5.8.0
* Python version: 3.9.9, also 3.8.12
* Type: core

## Description

This results in a segfault:

```python
import psutil; psutil.disk_partitions()
```

I've downgraded with `pip install psutil==5.7.3`; version 5.7.3 is fine.

**Comment by Huite** [comment] 2021-12-23 17:43
I just came back home from the office and retried: unfortunately it doesn't appear to be deterministic.

I can run the python lines above just fine now. (This makes sense to me personally at least, because I could work with downstream packages just fine yesterday evening, but not this morning while I hadn't updated these packages!)

**Comment by giampaolo** [comment] 2021-12-23 17:49
Duplicate of #1953.

**Closed by giampaolo** 2021-12-23 17:49 UTC
Labels: bug, windows, priority-high
