### ISSUE TITLE
cpu_count(logical=False) broken on multi-socket systems

### ISSUE THREAD

**Issue by FabioLuporini** [giampaolo/psutil#1558] opened 2019-07-26 10:15 UTC
**Platform**
Dual-socket Intel node made of ``Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz``
There are 48 logical CPUs and 24 physical CPUs (split over two sockets)
(if you want, I can share the full output of ``lscpu``)

* CentOS 7 (Core)
* 5.6.3

**Bug description**
``cpu_count(logical=False)`` returns 12, instead of 24.

Not consistent with ``cpu_count()``, which reports the total number of logical cores (across all sockets), that is 48.

to reproduce
```
import psutil
psutil.cpu_count(logical=False)
```

I've tried removing ``Method 1`` [here](https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py#L619)
and then it would work, reporting 24

I can PR it if you're happy to drop Method 1, otherwise not sure what I should do

**Comment by giampaolo** [comment] 2020-09-24 16:31
Closing as a duplicate of #1620. (let's continue there and/or the related PR)

**Closed by giampaolo** 2020-09-24 16:31 UTC
Labels: bug
