### ISSUE TITLE
psutil compatibility on Windows Nano Server

### ISSUE THREAD

**Issue by alexpilotti** [giampaolo/psutil#693] opened 2015-09-30 08:57 UTC
psutil does not work on Nano Server, failing to load due to a missing DLL (wtsapi32) and some PSAPI exports:
- Usage of wtsapi32 API. Nano Server does not have any GUI related features, so Remote Desktop APIs are not included. This means that psutil_users needs to be rewritten using different APIs or dinamically load the function addresses (GetProcAddress) when not running on Nano.
- Missing PSAPI_VERSION 1 functions. On the currently available TP3 release, only PSAPI_VERSION 2 APIs are included. This is most probably going to be fixed in the Nano forwarders in the upcoming releases, so hopefully no changes will be required in psutil. 

Here's a quick patch that adds Nano Server TP3 compatibility by simply removing the psutil_users implementation and setting PSAPI_VERSION = 2. This is just meant as a PoC as psutil_users will need to be fleshed out before a PR:

https://github.com/cloudbase/psutil/commit/32053d8c5bdcde22c7b23b7558e9386d06794a09

Thanks!

**Comment by giampaolo** [comment] 2016-05-31 22:27
Wow! This is old and totally slipped under my radar, sorry. I'm not sure if you're still interested into this, but if your patch doesn't break other Windows versions I'm OK with merging it.

**Comment by giampaolo** [comment] 2016-05-31 22:27
PS: next time please make a PR. They are more "noticeable".

**Comment by giampaolo** [comment] 2016-11-19 03:04
Useful link: https://msdn.microsoft.com/en-us/library/aa383056(v=vs.85).aspx

**Comment by giampaolo** [comment] 2016-11-19 03:16
I cannot reproduce this due to lack of hardware, but I can try to change the C function so that it dynamically loads the necessary functions. Would you be able to test this if I do?

**Comment by alexpilotti** [comment] 2016-11-19 08:21
Sure, I can definitely test it!

**Comment by smile21prc** [comment] 2017-04-11 17:52
Hi @giampaolo, I also needs this fix -- has it been merged already? I still see error below with psyutil 5.2.1 on Nano.

...
    import psutil
  File "C:\Python\lib\site-packages\psutil\__init__.py", line 126, in <module>
    from . import _pswindows as _psplatform
  File "C:\Python\lib\site-packages\psutil\_pswindows.py", line 16, in <module>
    from . import _psutil_windows as cext
ImportError: DLL load failed: The specified module could not be found.

**Comment by giampaolo** [comment] 2017-04-12 12:42
No, the original patch has never been applied. I would like to see a solution which does not involve disabling `users()` as the original patch does. Also I still haven't tested whether setting `('PSAPI_VERSION', 2)` has repercussions on other Windows versions.

**Comment by giampaolo** [comment] 2017-04-12 13:01
@alexpilotti what happens if you do not comment the `psutil_users` function? If users cannot be determined on Windows Nano it would also be OK to return an empty list.

**Comment by alexpilotti** [comment] 2017-04-12 13:42
@giampaolo it doesn't even load the pyd DLL because the wtsapi32 API are not available on Nano:

`ImportError: DLL load failed: The specified module could not be found.`

The easiest solution is to dynamically load the wtsapi32 DLL and simply return an error if the DLL is not available. The alternative would be to rewrite psutil_users using different API which are available on Nano as well.

**Comment by giampaolo** [comment] 2017-04-12 13:46
I'm +1 about removing the wtsapi32 header dependency, dynamically load wtsapi32 at runtime and return RuntimeError if it can't be loaded (Nano). My only concern is setting PSAPI_VERSION = 2 as I'm not sure what's gonna happen on older Windows versions (e.g. Vista).
Is it possible to fix Nano compatibility without setting PSAPI_VERSION = 2?

**Comment by alexpilotti** [comment] 2017-04-12 13:57
We are going to check if the older PSAPI are available on the current Nano release, the issue has been opened after testing on TP3.

**Comment by giampaolo** [comment] 2017-04-12 14:13
Unfortunately by removing `wtsapi32.h` the compiler also complains about missing `WTS_CURRENT_SERVER_HANDLE`, `WTS_CONNECTSTATE_CLASS`, `WTSClientAddress` and others.

**Comment by giampaolo** [comment] 2017-04-12 14:17
How can psutil be installed on Nano? Via pip? Do the pre-compiled exes-wheels work on Nano?
Because if they don't and the only way to install psutil on Nano is via sources we can use the C pre-processor and do something like this:

#ifdef __WinNano__
static PyObject *
psutil_users(PyObject *self, PyObject *args) {
        return PyErr_SetString(PyExc_RuntimeError, "wtsapi32.dll cannot be found");
}
...
#endif
```

**Comment by alexpilotti** [comment] 2017-04-12 14:28
Yes pip works on Nano, no need to remove wtsapi32.h from the headers, just the actual calls to the functions need to be replaced with dynamic ones (GetProcAddress). The DLL fails to load due to the missing imports.

**Comment by giampaolo** [comment] 2017-04-12 14:31
So `wtsapi32.h` can be left in place in the C extension but `"wtsapi32"` should be removed from setup.py?

**Comment by alexpilotti** [comment] 2017-04-12 14:36
Correct, as an example, here's the commit that we are currently applying: https://github.com/cloudbase/psutil/commit/602e8a81958affb73b7ae6afe1cb32078cf42122

**Comment by giampaolo** [comment] 2017-04-12 14:55
But how do you install psutil on Nano? Via source or via wheels?

**Comment by alexpilotti** [comment] 2017-04-12 15:15
wheels, there's no compiler on Nano

**Comment by albertvaka** [comment] 2020-05-21 15:59
I guess this hasn't been implemented yet? Is it blocked?

Currently, we are getting this error when importing psutil on Windows Nano:
```
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ImportError: DLL load failed while importing _psutil_windows: The specified procedure could not be found.
```

**Comment by giampaolo** [comment] 2020-12-29 02:05
Fixed in https://github.com/giampaolo/psutil/pull/1768.

**Closed by giampaolo** 2020-12-29 02:05 UTC
Labels: enhancement, priority-high, windows
