### ISSUE TITLE
Solaris: get UNIX sockets in C

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#493] opened 2014-05-23 15:20 UTC
_From [g.rodola](https://code.google.com/u/g.rodola/) on April 08, 2014 00:11:25_
    
    ...as of now we parse "pfiles" command output.
    
_Original issue: http://code.google.com/p/psutil/issues/detail?id=493_

**Comment by wiggin15** [comment] 2015-04-29 21:36
Hi. Just wanted to mention that this is a duplicate of #409 so this ticket can be closed.

**Closed** 2015-04-29 21:39 UTC
Labels: enhancement, imported, OpSys-Solaris, Priority-Low
