### ISSUE TITLE
Return number of numa nodes

### ISSUE THREAD

**Issue by santagada** [giampaolo/psutil#1610] opened 2019-10-21 17:13 UTC
Add a function like cpu_count but numa_count(), and on windows also a groups_count() could be very handy.

**Comment by Porges** [comment] 2020-02-03 22:22
It would be nice to also have physical CPU count, since the code to do this on Windows is rather gnarly and requires dropping to `ctypes`.

**Comment by giampaolo** [comment] 2020-02-03 22:27
> It would be nice to also have physical CPU count

`cpu_count(logical=False)` is supposed to do it.

Back to the original requrst: is there an actualy use case for NUMA nodes or it would just be for display (e.g. task manager apps)? Also, what do you mean by `groups_count()`?

**Comment by Porges** [comment] 2020-02-03 23:32
@giampaolo that is physical core count, not CPU count.

**Comment by giampaolo** [comment] 2020-02-04 00:11
Oh! Socket count. Mmm... That sounds sort of low levelish (would it really be useful?). Does Windows provide an API for this? I'm not sure we can support other platforms other than Windows. 

Also (perhaps a personal consideration): the definition of what a CPU count really means is a bit confusing. The definition I ad-here to is this:
https://www.sqlskills.com/blogs/glenn/what-is-the-difference-between-physical-sockets-physical-cores-and-logical-cores/
...so 3 kinds:

1) **socket count** = number of sockets on the motherboard 
2) **physical count** = number of physical CPU cores (can have more than 1 per socket)
3) **logical count** = physical count * number of hyper threading cores (hyper threading = INTEL's way to make 1 processor look like many processors)
 
psutil currently [supports 2 and 3](https://psutil.readthedocs.io/en/latest/#psutil.cpu_count).

**Comment by santagada** [comment] 2020-05-10 15:07
if you have more than 64 logical cpus, windows will put them on different groups, as an affinity mask is 64 bits (so you can only turn on and off 64 cpus). Knowing the group_count on windows is useful. More useful is the total logical cpus in all numa nodes, IIRC cpu_count() only return the number of logical cpu on the first numa node.

**Comment by giampaolo** [comment] 2020-05-10 15:50
> if you have more than 64 logical cpus, windows will put them on different groups, as an affinity mask is 64 bits (so you can only turn on and off 64 cpus).

Are you sure? On Windows cpu_logical() is implemented by using `GetActiveProcessorCount(ALL_PROCESSOR_GROUPS)`. The name suggests all groups should be included. 
https://github.com/giampaolo/psutil/blob/9e2ca978b211993066b0dc41da9aa63429655406/psutil/arch/windows/cpu.c#L24

As for NUMA: I'm no expert. Is it something which exists in Windows only?

**Comment by akrus** [comment] 2020-06-30 06:26
One small note on NUMA nodes, it's not equal to socket count, e.g. 2x AMD EPYC 7601:
```
# numactl --hardware                                                                                                                                                     
available: 8 nodes (0-7)
```

And it depends on BIOS settings (Node Interleaving and a few more options for AMD CPUs).

In Linux you can get the info from sysfs:
```
# ls -1 /sys/devices/system/node/                                                                                                                                                                                         
has_cpu                                                                                                                                                                                                                                      
has_memory
has_normal_memory
node0
node1
node2
node3
node4
node5
node6
node7
online
possible
power
uevent
```

**Comment by giampaolo** [comment] 2020-12-29 00:30
Closing as duplicate of #1392.

**Closed by giampaolo** 2020-12-29 00:30 UTC
Labels: enhancement
