### ISSUE TITLE
AccessDenied exception is not caught when trying to compare process ids (pids) in a system where SElinux is set to 'enforcing'

### ISSUE THREAD

**Issue by coderbunty** [giampaolo/psutil#1246] opened 2018-03-14 15:42 UTC
While collecting Guru Meditation report (GMR) using "kill -USR2 <pid>" command on a system configured with SELinux in 'enforcing' mode we get the below error stack trace
```
nova-api: Traceback (most recent call last):
nova-api: File "/usr/lib/python2.7/site-packages/oslo_reports/guru_meditation_report.py", line 211, in handle_signa        l
nova-api: res = cls(version, frame).run()
nova-api: File "/usr/lib/python2.7/site-packages/oslo_reports/guru_meditation_report.py", line 259, in run
nova-api: return super(GuruMeditation, self).run()
nova-api: File "/usr/lib/python2.7/site-packages/oslo_reports/report.py", line 77, in run
nova-api: return "\n".join(six.text_type(sect) for sect in self.sections)
nova-api: File "/usr/lib/python2.7/site-packages/oslo_reports/report.py", line 77, in <genexpr>
nova-api: return "\n".join(six.text_type(sect) for sect in self.sections)
nova-api: File "/usr/lib/python2.7/site-packages/oslo_reports/report.py", line 102, in __str__
nova-api: return self.view(self.generator())
nova-api: File "/usr/lib/python2.7/site-packages/oslo_reports/report.py", line 131, in newgen
nova-api: res = gen()
nova-api: File "/usr/lib/python2.7/site-packages/oslo_reports/generators/process.py", line 38, in __call__
nova-api: return pm.ProcessModel(psutil.Process(os.getpid()))
nova-api: File "/usr/lib/python2.7/site-packages/oslo_reports/models/process.py", line 66, in __init__
nova-api: children = process.children()
nova-api: File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 336, in wrapper
nova-api: return fun(self, *args, **kwargs)
nova-api: File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 913, in children
nova-api: **if p.ppid() == self.pid:**
nova-api: File "/usr/lib64/python2.7/site-packages/psutil/_common.py", line 293, in wrapper
nova-api: return fun(self)
nova-api: File "/usr/lib64/python2.7/site-packages/psutil/__init__.py", line 622, in ppid
nova-api: return self._proc.ppid()
nova-api: File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 1092, in wrapper
nova-api: **raise AccessDenied(self.pid, self._name)**
nova-api: **AccessDenied: psutil.AccessDenied (pid=1)**
nova-api: **Unable to run Guru Meditation Report!**
```
This happens because the nova-api process is trying to locate a specific dir (pid number) in /proc & it compares every dir with the dir it wants to find. In this process, it encounters one directory for which it is not having access/search privilege according to SELinux rules and as psutils didnot catch this "AccessDenied" exception, the whole thing fails. Ideally, we would want to catch this exception and proceed with the search.

I think we need to also catch 'AccessDenied' exception in https://github.com/giampaolo/psutil/blob/master/psutil/__init__.py#L904.

**Comment by giampaolo** [comment] 2018-03-14 15:47
Mmm... from the stack trace I see this is an older psutil version. What version is it?
Ideally it would be great if you can install latest GIT version of psutil (git clone it) then repaste the traceback.

**Comment by coderbunty** [comment] 2018-03-14 15:58
This is python-psutil-5.0.1-2. I won't be able to install the latest version of psutils in my environment due to compatibility issues. However, on the latest version also this problem would exist i guess.

**Comment by giampaolo** [comment] 2018-03-14 16:15
So, the problem here is that the user doesn't have permission to read `/proc/{PID}/stat` for some reason. This is unusual, as I'm able to query /stat for all PIDs (on Ubuntu) so it must be SELinux which has restrictive security policies by default. The same problem should apply to tools such as `ps` and `top` but I suppose SELinux runs them with the sticky bit set in order to work around this issue.
As far as psutil goes there is nothing we can do. psutil is doing the "right thing". Catching the exception and ignoring it wouldn't be good.
The only workaround here, IMO, is to either run Python with root privileges or change the permissions of /proc fs somehow.

**Comment by coderbunty** [comment] 2018-03-14 16:21
I am not suggesting to ignore any exceptions here. All I am saying is to catch 'AccessDenied' exception too in
https://github.com/giampaolo/psutil/blob/master/psutil/__init__.py#L904

**Comment by giampaolo** [comment] 2018-03-14 16:21
That means ignoring it.

**Comment by coderbunty** [comment] 2018-03-14 16:40
This SELinux restriction due to which nova_api like processes cannot have access to /proc/1  will be there in all RHEL machines and is justified too as we don't want any non-root user to be accessing init process directory in /proc.
Also, when you say "psutil is doing the "right thing". Catching the exception and ignoring it wouldn't be good.", why wouldn't it be good? I am trying to understand what problems might occur.

**Comment by giampaolo** [comment] 2018-03-14 16:51
AFAIK, RHEL should not behave like this. `/proc/{PID}/stat` is usually readable by user on most Linux distros as it contains vital process information which shouldn't really represent a security concern. It basically has the process name + many metrics such as CPU times, memory info, etc which are useful for system  monitoring tools such as `ps` and `top` (and psutil):

```
$ cat /proc/1/stat
1 (systemd) S 0 1 1 0 -1 4194560 70659 12381236 119 1747 337 348 250945 569145 20 0 1 0 5 189927424 1338 18446744073709551615 1 1 0 0 0 0 671173123 4096 1260 0 0 0 17 5 0 0 38786079 0 0 0 0 0 0 0 0 0 0
```

There really are tons of Linux tools out there relying on `/proc/{PID}/stat` so I wouldn't say this restriction is really justified as they inherit the exact same issue. 

As for ignoring the exception, that wouldn't be good because `Process.children()` may return an incomplete result. Also Python Zen says that "errors should never pass silently". =)

**Comment by giampaolo** [comment] 2018-03-17 07:13
Closing as "not a bug".

**Closed by giampaolo** 2018-03-17 07:13 UTC

**Comment by kumarBiplab1987** [comment] 2018-04-02 17:25
@giampaolo adding to this discussion I found in the error log  that the exception came while opening /proc/1/stat file by psutil. However when I am trying it in python prompt it doesn't restricting me to open the file
Not sure why selinux restricting to open a file for read in psutil .Here is the logs:

['Traceback (most recent call last):\n', '  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 1126, in _parse_stat_file\n    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:\n', '  File "/usr/lib64/python2.7/site-packages/psutil/_pslinux.py", line 182, in open_binary\n    return open(fname, "rb", **kwargs)\n', "IOError: [Errno 13] Permission denied: '/proc/1/stat'\n"]0: IOError: [Errno 13] Permission denied: '/proc/1/stat'

**Comment by dikonoor** [comment] 2018-04-03 07:45
@kumarBiplab1987, SELinux is different from file permissions. When you try to open the file from python prompt, the selinux type associated with the process attempting to open the file is different from what's reported in this defect. SELinux reports permission denied because the process (which seems to be an OpenStack service in the context of this defect), that has invoked oslo report library does not have access to this file from a SELinux context.
