### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'psutil>=5.7.0; sys_platform != "win32" or platform_python_implementation == "CPython" and extra == "recommended"' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by lavisco** [giampaolo/psutil#1938] opened 2021-04-26 08:59 UTC
## Summary

* OS: { Ubuntu 20.04 }
* Architecture: { 64bit }
* Psutil version: { pip3 show psutil }
* Python version: { Python 3.8.5 }
* Type: { performance }

## Description
I am facing this issue while using docker-compose up command
```
$ docker-compose up
Starting ruqqus_postgres_1 ... done
Starting ruqqus_redis_1    ... done
Starting ruqqus_ruqqus_1   ... done
Attaching to ruqqus_redis_1, ruqqus_postgres_1, ruqqus_ruqqus_1
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
redis_1     | 1:C 26 Apr 2021 08:49:44.899 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 26 Apr 2021 08:49:44.899 # Redis version=6.2.2, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 26 Apr 2021 08:49:44.899 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1     | 1:M 26 Apr 2021 08:49:44.901 * monotonic clock: POSIX clock_gettime
postgres_1  | 2021-04-26 08:49:45.107 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
redis_1     | 1:M 26 Apr 2021 08:49:44.902 * Running mode=standalone, port=6379.
redis_1     | 1:M 26 Apr 2021 08:49:44.902 # Server initialized
redis_1     | 1:M 26 Apr 2021 08:49:44.902 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 26 Apr 2021 08:49:44.903 * Loading RDB produced by version 6.2.2
redis_1     | 1:M 26 Apr 2021 08:49:44.903 * RDB age 184443 seconds
redis_1     | 1:M 26 Apr 2021 08:49:44.903 * RDB memory usage when created 0.77 Mb
redis_1     | 1:M 26 Apr 2021 08:49:44.904 * DB loaded from disk: 0.001 seconds
redis_1     | 1:M 26 Apr 2021 08:49:44.904 * Ready to accept connections
postgres_1  | 2021-04-26 08:49:45.107 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2021-04-26 08:49:45.107 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2021-04-26 08:49:45.122 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-04-26 08:49:45.166 UTC [26] LOG:  database system was interrupted; last known up at 2021-04-26 08:26:04 UTC
postgres_1  | 2021-04-26 08:49:45.304 UTC [26] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1  | 2021-04-26 08:49:45.311 UTC [26] LOG:  redo starts at 0/18AA7A0
postgres_1  | 2021-04-26 08:49:45.311 UTC [26] LOG:  invalid record length at 0/18AA7D8: wanted 24, got 0
postgres_1  | 2021-04-26 08:49:45.311 UTC [26] LOG:  redo done at 0/18AA7A0
postgres_1  | 2021-04-26 08:49:45.348 UTC [1] LOG:  database system is ready to accept connections
ruqqus_1    | 2021-04-26 08:49:46,188 CRIT Supervisor running as root (no user in config file)
ruqqus_1    | 2021-04-26 08:49:46,192 INFO supervisord started with pid 1
ruqqus_1    | 2021-04-26 08:49:47,197 INFO spawned: 'ruqqusservice' with pid 11
ruqqus_1    | Traceback (most recent call last):
ruqqus_1    |   File "/usr/local/bin/gunicorn", line 11, in <module>
ruqqus_1    |     sys.exit(run())
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
ruqqus_1    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 231, in run
ruqqus_1    |     super().run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
ruqqus_1    |     Arbiter(self).run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 58, in __init__
ruqqus_1    |     self.setup(app)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 118, in setup
ruqqus_1    |     self.app.wsgi()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
ruqqus_1    |     self.callable = self.load()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
ruqqus_1    |     return self.load_wsgiapp()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ruqqus_1    |     return util.import_app(self.app_uri)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 359, in import_app
ruqqus_1    |     mod = importlib.import_module(module)
ruqqus_1    |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ruqqus_1    |     return _bootstrap._gcd_import(name[level:], package, level)
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
ruqqus_1    |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ruqqus_1    |   File "/opt/ruqqus/service/ruqqus/__main__.py", line 2, in <module>
ruqqus_1    |     gevent.monkey.patch_all()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 1228, in patch_all
ruqqus_1    |     _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 185, in _notify_patch
ruqqus_1    |     notify_and_call_entry_points(event)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/events.py", line 104, in notify_and_call_entry_points
ruqqus_1    |     subscriber = plugin.load()
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
ruqqus_1    |     self.require(*args, **kwargs)
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require
ruqqus_1    |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
ruqqus_1    |     raise DistributionNotFound(req, requirers)
ruqqus_1    | pkg_resources.DistributionNotFound: The 'psutil>=5.7.0; sys_platform != "win32" or platform_python_implementation == "CPython" and extra == "monitor"' distribution was not found and is required by the application
ruqqus_1    | 2021-04-26 08:49:48,068 INFO exited: ruqqusservice (exit status 1; not expected)
ruqqus_1    | 2021-04-26 08:49:49,073 INFO spawned: 'ruqqusservice' with pid 14
ruqqus_1    | Traceback (most recent call last):
ruqqus_1    |   File "/usr/local/bin/gunicorn", line 11, in <module>
ruqqus_1    |     sys.exit(run())
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
ruqqus_1    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 231, in run
ruqqus_1    |     super().run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
ruqqus_1    |     Arbiter(self).run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 58, in __init__
ruqqus_1    |     self.setup(app)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 118, in setup
ruqqus_1    |     self.app.wsgi()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
ruqqus_1    |     self.callable = self.load()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
ruqqus_1    |     return self.load_wsgiapp()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ruqqus_1    |     return util.import_app(self.app_uri)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 359, in import_app
ruqqus_1    |     mod = importlib.import_module(module)
ruqqus_1    |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ruqqus_1    |     return _bootstrap._gcd_import(name[level:], package, level)
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
ruqqus_1    |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ruqqus_1    |   File "/opt/ruqqus/service/ruqqus/__main__.py", line 2, in <module>
ruqqus_1    |     gevent.monkey.patch_all()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 1228, in patch_all
ruqqus_1    |     _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 185, in _notify_patch
ruqqus_1    |     notify_and_call_entry_points(event)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/events.py", line 104, in notify_and_call_entry_points
ruqqus_1    |     subscriber = plugin.load()
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
ruqqus_1    |     self.require(*args, **kwargs)
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require
ruqqus_1    |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
ruqqus_1    |     raise DistributionNotFound(req, requirers)
ruqqus_1    | pkg_resources.DistributionNotFound: The 'psutil>=5.7.0; sys_platform != "win32" or platform_python_implementation == "CPython" and extra == "test"' distribution was not found and is required by the application
ruqqus_1    | 2021-04-26 08:49:49,725 INFO exited: ruqqusservice (exit status 1; not expected)
ruqqus_1    | 2021-04-26 08:49:51,731 INFO spawned: 'ruqqusservice' with pid 17
ruqqus_1    | Traceback (most recent call last):
ruqqus_1    |   File "/usr/local/bin/gunicorn", line 11, in <module>
ruqqus_1    |     sys.exit(run())
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
ruqqus_1    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 231, in run
ruqqus_1    |     super().run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
ruqqus_1    |     Arbiter(self).run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 58, in __init__
ruqqus_1    |     self.setup(app)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 118, in setup
ruqqus_1    |     self.app.wsgi()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
ruqqus_1    |     self.callable = self.load()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
ruqqus_1    |     return self.load_wsgiapp()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ruqqus_1    |     return util.import_app(self.app_uri)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 359, in import_app
ruqqus_1    |     mod = importlib.import_module(module)
ruqqus_1    |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ruqqus_1    |     return _bootstrap._gcd_import(name[level:], package, level)
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
ruqqus_1    |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ruqqus_1    |   File "/opt/ruqqus/service/ruqqus/__main__.py", line 2, in <module>
ruqqus_1    |     gevent.monkey.patch_all()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 1228, in patch_all
ruqqus_1    |     _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 185, in _notify_patch
ruqqus_1    |     notify_and_call_entry_points(event)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/events.py", line 104, in notify_and_call_entry_points
ruqqus_1    |     subscriber = plugin.load()
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
ruqqus_1    |     self.require(*args, **kwargs)
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require
ruqqus_1    |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
ruqqus_1    |     raise DistributionNotFound(req, requirers)
ruqqus_1    | pkg_resources.DistributionNotFound: The 'psutil>=5.7.0; sys_platform != "win32" or platform_python_implementation == "CPython" and extra == "recommended"' distribution was not found and is required by the application
ruqqus_1    | 2021-04-26 08:49:52,354 INFO exited: ruqqusservice (exit status 1; not expected)
ruqqus_1    | 2021-04-26 08:49:55,361 INFO spawned: 'ruqqusservice' with pid 20
ruqqus_1    | Traceback (most recent call last):
ruqqus_1    |   File "/usr/local/bin/gunicorn", line 11, in <module>
ruqqus_1    |     sys.exit(run())
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
ruqqus_1    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 231, in run
ruqqus_1    |     super().run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
ruqqus_1    |     Arbiter(self).run()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 58, in __init__
ruqqus_1    |     self.setup(app)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 118, in setup
ruqqus_1    |     self.app.wsgi()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
ruqqus_1    |     self.callable = self.load()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
ruqqus_1    |     return self.load_wsgiapp()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
ruqqus_1    |     return util.import_app(self.app_uri)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 359, in import_app
ruqqus_1    |     mod = importlib.import_module(module)
ruqqus_1    |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ruqqus_1    |     return _bootstrap._gcd_import(name[level:], package, level)
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
ruqqus_1    |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
ruqqus_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ruqqus_1    |   File "/opt/ruqqus/service/ruqqus/__main__.py", line 2, in <module>
ruqqus_1    |     gevent.monkey.patch_all()
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 1228, in patch_all
ruqqus_1    |     _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/monkey.py", line 185, in _notify_patch
ruqqus_1    |     notify_and_call_entry_points(event)
ruqqus_1    |   File "/usr/local/lib/python3.6/dist-packages/gevent/events.py", line 104, in notify_and_call_entry_points
ruqqus_1    |     subscriber = plugin.load()
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
ruqqus_1    |     self.require(*args, **kwargs)
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require
ruqqus_1    |     items = working_set.resolve(reqs, env, installer, extras=self.extras)
ruqqus_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
ruqqus_1    |     raise DistributionNotFound(req, requirers)
ruqqus_1    | pkg_resources.DistributionNotFound: The 'psutil>=5.7.0; sys_platform != "win32" or platform_python_implementation == "CPython" and extra == "recommended"' distribution was not found and is required by the application
ruqqus_1    | 2021-04-26 08:49:55,996 INFO exited: ruqqusservice (exit status 1; not expected)
ruqqus_1    | 2021-04-26 08:49:56,998 INFO gave up: ruqqusservice entered FATAL state, too many start retries too quickly
```

**Comment by giampaolo** [comment] 2021-10-05 17:44
Not a bug related to psutil. Closing.

**Closed by giampaolo** 2021-10-05 17:44 UTC
Labels: bug, windows, linux, performance
