### ISSUE TITLE
OSError: [WinError 0] The operation completed successfully

### ISSUE THREAD

**Issue by fenchu** [giampaolo/psutil#1405] opened 2019-02-08 14:22 UTC
Why does _pswindows.py give this Exception. running as administrator, as plain user it works all fine:
If you had called it OSError.Success I could have filtered it out.

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18329 N/A Build 18329
```

```
    pids = psutil.pids()
    for pid in pids:
        print("process:{}".format(psutil.Process(pid)))
```

```
process:psutil.Process(pid=0, name='System Idle Process', started='2019-02-06 17:48:07')
process:psutil.Process(pid=4, name='System', started='2019-02-06 17:48:07')
Traceback (most recent call last):
  File ".\proxylog2elastic.py", line 233, in <module>
    print("process:{}".format(psutil.Process(pid)))
  File "d:\dev\sensiotools\lib\site-packages\psutil\__init__.py", line 395, in __str__
    info["name"] = self.name()
  File "d:\dev\sensiotools\lib\site-packages\psutil\__init__.py", line 609, in name
    name = self._proc.name()
  File "d:\dev\sensiotools\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
    return fun(self, *args, **kwargs)
  File "d:\dev\sensiotools\lib\site-packages\psutil\_pswindows.py", line 687, in name
    return py2_strencode(os.path.basename(self.exe()))
  File "d:\dev\sensiotools\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
    return fun(self, *args, **kwargs)
  File "d:\dev\sensiotools\lib\site-packages\psutil\_pswindows.py", line 701, in exe
    return py2_strencode(convert_dos_path(cext.proc_exe(self.pid)))
OSError: [WinError 0] The operation completed successfully

(sensiotools) PS D:\sensio-data\sensiotools\sensiotools\elasticsearch> python.exe
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.__version__
'5.5.0'
```

**Comment by giampaolo** [comment] 2019-02-08 14:28
This is a duplicate of https://github.com/giampaolo/psutil/issues/1394. I should be able to release a fixed version next week, as I consider this a high-priority bug. For the time being you may want to downgrade to the previous version.

**Closed by giampaolo** 2019-02-08 14:28 UTC
