### ISSUE TITLE
[Ubuntu 14.04] Not compiling on pip3 install psutil

### ISSUE THREAD

**Issue by keysersoza** [giampaolo/psutil#1918] opened 2021-02-19 12:14 UTC
## Summary

* OS: { Ubuntu 14.04 }
* Architecture: { 64bit }
* Psutil version: { psutil 5.4.6 }
* Python version: { python3.4 }
* Type: { installation}

## Description

Hi,
I am trying to install psutil on my ubuntu 14.04 machine which has python 3.4 installed.
I am using a requirements.txt file, the latest version I could find for psutil on py3.4 is 5.4.6.

I've installed python3.4-dev, but when I pip install it I get the following error:
```

/usr/bin/ld: cannot find -lssl

/usr/bin/ld: cannot find -lcrypto

collect2: error: ld returned 1 exit status

error: command 'x86_64-linux-gnu-g++' failed with exit status 1
```

Is it missing some libraries?

Thanks.

**Comment by giampaolo** [comment] 2021-04-09 15:23
Very old distro and old psutil version. I don't know. Closing out as "not a bug".

**Closed by giampaolo** 2021-04-09 15:23 UTC
Labels: bug, linux
