### ISSUE TITLE
Psutil on bash for Windows

### ISSUE THREAD

**Issue by jorgii** [giampaolo/psutil#820] opened 2016-05-19 09:36 UTC
I happened to use psutil on basah for windows and I noticed that a few things are not working. Here is what I found:

```
>>> psutil.disk_partitions()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "***/lib/python3.4/site-packages/psutil/__init__.py", line 1801, in disk_partitions
    return _psplatform.disk_partitions(all)
  File "***/lib/python3.4/site-packages/psutil/_pslinux.py", line 899, in disk_partitions
    fstype = line.split("\t")[1]
IndexError: list index out of range
```

```
>>> psutil.cpu_count(logical=False)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "***/lib/python3.4/site-packages/psutil/_common.py", line 123, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "***/lib/python3.4/site-packages/psutil/__init__.py", line 1477, in cpu_count
    return _psplatform.cpu_count_physical()
  File "***/lib/python3.4/site-packages/psutil/_pslinux.py", line 454, in cpu_count_physical
    key, value = line.split(b'\t:', 1)
ValueError: need more than 1 value to unpack
```

I am using Windows 10 build 14342.1000

Let me know what other information I can provide to help fix it.

**Comment by giampaolo** [comment] 2016-05-19 13:29
Wow, this is crazy! So this is how it is supposed to work? psutil on Windows 10 + bash ends up using the Linux implementation? I had no idea. Thanks for reporting this. 
As far as I am concerned: my plan for future development on Windows consists in using Win 10 in order to take advantage of bash and ease up my workflow (especially for SSH). I can take a look at this once I install Win 10 on VirtualBox (+ VS).
As for your errors: I suppose a lot more than that will break if you run `make test`.

**Comment by jorgii** [comment] 2016-06-03 08:21
Yup, actually python thinks that I am using Ubuntu when I ask for the OS within python. 
Anyways, I ran the tests and here are the results:
[psutil_testresults.txt](https://github.com/giampaolo/psutil/files/297193/psutil_testresults.txt)

That's not in any way blocking me so no rush from my side.

**Comment by giampaolo** [comment] 2020-12-29 01:58
Duplicate of https://github.com/giampaolo/psutil/issues/1251.

**Closed by giampaolo** 2020-12-29 01:58 UTC
Labels: enhancement, windows
