### ISSUE TITLE
sensors_temperatures()  not support  Double CPU 

### ISSUE THREAD

**Issue by wanghaiqing2015** [giampaolo/psutil#1108] opened 2017-07-12 09:11 UTC
error message:
No such file or directory: '/sys/class/hwmon/hwmon0/device/name'

use lm_sensors is ok, show:

       coretemp-isa-0000
       coretemp-isa-0001

**Comment by giampaolo** [comment] 2017-09-08 07:45
Please paste the output of `ls /sys/class/hwmon/hwmon*/temp*_*` and `/sys/class/hwmon/hwmon*/device/temp*_*`.

**Comment by giampaolo** [comment] 2017-09-27 17:05
This should be a duplicate of https://github.com/giampaolo/psutil/issues/1129. Closing.

**Closed by giampaolo** 2017-09-27 17:05 UTC
Labels: bug, OpSys-Linux
