### ISSUE TITLE
Inaccurate reporting of process creation time via create_time() under Linux

### ISSUE THREAD

**Issue by ChaoticMind** [giampaolo/psutil#877] opened 2016-08-29 13:04 UTC
It looks like the value reported in psutil via `create_time()` is inaccurate under Linux. It's too far in the past (by less than a second, in my tests). It looks like the offset is constant across various runs. I only tested this on Linux (both debian and arch). The issue appears in both python2 and python3.

I wrote a sample script to illustrate the problem. The script forks a new process and then fetches the new process' creation time. You'll notice that the reported `create_time()` of the forked process is too far back in the past: older than the current timestamp at the beginning of the script. For comparison, I also printed out the timestamp for the folder creation obtained via the `stat` command on `/proc/<pid>` (well, modification time, I couldn't get the creation time for some reason, but this is not relevant to the issue).

``` python
#!/usr/bin/env python3
import subprocess
import datetime

import psutil

PROCESS_TO_FORK = "python3"


def main():
    initial_time = datetime.datetime.now()
    print("time now: {}".format(initial_time))
    p = subprocess.Popen(
        PROCESS_TO_FORK,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL)
    proc = psutil.Process(p.pid)
    stat_out = subprocess.check_output(
        ['stat', '-c', '%y', '/proc/{}'.format(p.pid)])

    ct = datetime.datetime.fromtimestamp(proc.create_time())
    print("create_time from psutil: {}".format(ct))
    print("create_time from stat: {}".format(stat_out.decode("utf-8")))
    print("process uptime according to psutil: {}".format(
        (datetime.datetime.now() - ct).total_seconds()))

    end_time = datetime.datetime.now()
    print("time now: {}".format(end_time))
    print("script runtime: {}s".format(
        (end_time - initial_time).total_seconds()))


if __name__ == '__main__':
    main()
```

A sample output would be:

```
$ time ./test_create.py
time now: 2016-08-29 14:38:52.471206
create_time from psutil: 2016-08-29 14:38:51.930000
create_time from stat: 2016-08-29 14:38:52.469848115 +0200

process uptime according to psutil: 0.543344
time now: 2016-08-29 14:38:52.473368
script runtime: 0.002162s
./test_create.py  0.07s user 0.00s system 97% cpu 0.072 total
```

As can be seen from the output, the process runtime is larger than the script runtime, which is impossible. Note that the time obtained from `stat` is also a bit in the past compared to the initial timestamp, so that's also wrong, but it's not off by as much. The fact that the resolution of create_time() seems to be many digits is misleading if its accuracy is actually within 1s.

Other tools seem to only show process creation-time/runtime up to a second accuracy. Is it impossible to get a more fine grained value? It seems unlikely because the offset/error is [almost] constant.

Reference: http://unix.stackexchange.com/questions/7870/how-to-check-how-long-a-process-has-been-running

**Comment by giampaolo** [comment] 2016-08-29 14:52
Hmmm... the fact that `proc.create_time()` tstamp is older than `datetime.datetime.now()` is normal because historically the process is created first (in the past), then `datetime.datetime.now()` is called (in the future).

What's weird is the 0.4 secs difference: the number is too high.
I can reproduce a similar behavior by using `time.time()` instead of `datetime`:

```
import psutil
import time
import os

print(time.time())
print(psutil.Process().create_time())
print(os.stat("/proc/%s" % os.getpid()).st_ctime)
```

...prints:

```
1472481342.6128926
1472481342.23
1472481342.601793
```

`st_ctime` from `os.stat` looks more accurate (`0.012` secs difference) so we may be tempted to use that one instead of parsing /proc/pid/stat output. The problem with that is that Linux fs does not store file creation time.

**Comment by giampaolo** [comment] 2016-08-29 15:00
Here's the ~0.4 secs difference:

```
~/svn/psutil {master}$ python3 -c "import time, psutil; print(time.time() - psutil.Process().create_time())"
0.3816211223602295
```

**Comment by giampaolo** [comment] 2017-06-09 12:34
I suppose there is nothing we can do about this. Closing it out.

**Closed by giampaolo** 2017-06-09 12:34 UTC
Labels: 64bit, bug, OpSys-Linux
