### ISSUE TITLE
Windows: OSError: [WinError 0] The operation completed successfully: '(originated from QueryFullProcessImageNameW)'

### ISSUE THREAD

**Issue by otrejoso** [giampaolo/psutil#1675] opened 2020-01-28 20:12 UTC
We were in the process to update to python 3.7 in our internal build/test machines, and one of our windows server 2008 started to get the following error:

```
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\testdriver\executor.py:84: in execute
[exec]     proc_name, mem, local_children = find_memory_usage(proc)
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\testdriver\performance_functions.py:74: in find_memory_usage
[exec]     children.add((c.pid, c.name()))
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\__init__.py:731: in name
[exec]     name = self._proc.name()
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\_pswindows.py:709: in wrapper
[exec]     raise convert_oserror(err, pid=self.pid, name=self._name)
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\_pswindows.py:699: in convert_oserror
[exec]     raise exc
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\_pswindows.py:707: in wrapper
[exec]     return fun(self, *args, **kwargs)
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\_pswindows.py:782: in name
[exec]     return py2_strencode(os.path.basename(self.exe()))
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\_pswindows.py:709: in wrapper
[exec]     raise convert_oserror(err, pid=self.pid, name=self._name)
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\_pswindows.py:699: in convert_oserror
[exec]     raise exc
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\_pswindows.py:707: in wrapper
[exec]     return fun(self, *args, **kwargs)
[exec] C:\_\k0\project\test\tests_pti\.pti_artifactory\venv\lib\site-packages\psutil\_pswindows.py:791: in exe
[exec]     exe = cext.proc_exe(self.pid)
[exec] E   OSError: [WinError 0] The operation completed successfully: '(originated from QueryFullProcessImageNameW)'
```
We are installing the latest psutil version `psutil-5.6.7-cp37-cp37m-win_amd64.whl `
It also looks very similar as https://github.com/giampaolo/psutil/issues/1394
Is this a bug or something we can work around?

**Comment by giampaolo** [comment] 2020-01-28 20:19
Dupe of #1662.

**Closed by giampaolo** 2020-01-28 20:19 UTC
Labels: bug
