### ISSUE TITLE
Wheels for Linux and Mac

### ISSUE THREAD

**Issue by ccordoba12** [giampaolo/psutil#900] opened 2016-10-02 08:33 UTC
Spyder has `psutil` as a dependency, so it's difficult for our users to pip-install Spyder on Linux and Mac because it requires a compiler in those platforms.

So I was wondering if you guys have plans to create wheels for those platforms, or if there's anything we can do to help with that :-)

**Comment by giampaolo** [comment] 2016-10-09 22:36
So, the way I do psutil development on OSX is yb virtualizing iDeneb (an old OSX 10.5 hack) via VirtualBox. It is too much of an effort for me to provide OSX binaries on every new release as I already do that for Windows via AppVeyor.

The only viable option (for me as a release manager at least) is to automatize the creation of dmg files (instead of doing it manually every time). We currently use Travis CI to run tests on Linux and OSX. I've never looked into it but it seems Travis is able to create and host files  similarly to AppVeyor:
https://docs.travis-ci.com/user/uploading-artifacts/

I currently don't have time to investigate how to set up a process to create dmg files on OSX but I am willing to accept pull requests, so if you want to give it a shot, you're welcome.

**Comment by giampaolo** [comment] 2016-11-16 17:56
Blog entry on how to have Travis create dmg (OSX) files: http://blog.fossasia.org/deploying-a-kivy-application-with-pyinstaller-for-mac-osx-to-github/

**Comment by giampaolo** [comment] 2019-03-25 22:50
Closing out as a duplicate of #824.

**Closed by giampaolo** 2019-03-25 22:50 UTC

**Comment by giampaolo** [comment] 2020-12-19 02:06
Solved in https://github.com/giampaolo/psutil/issues/1550#issuecomment-748401967.
