### ISSUE TITLE
Windows - psutil does not detect mounted folders without drive letters as disks

### ISSUE THREAD

**Issue by MattGirolami** [giampaolo/psutil#775] opened 2016-02-23 20:54 UTC
Windows supports assigning NTFS disks a mounted folder/mount point value instead of (or in addition to) a drive letter. Psutil does not recognize drives that only have a mount point and not a drive letter.

In the example below, I've attached and formatted a hard drive, but instead of assigning it it's own drive letter, I've assigned it a mount point path of C:\mountedfolder\ . I can iterate the drive in powershell/wmi:

```
C:\>  Get-WmiObject -namespace "root/cimv2" -query "SELECT Name, Capacity, FreeSpace, deviceid FROM Win32_Volume WHERE DriveType = 3" | select deviceid,name,capacity | format-list


deviceid : \\?\Volume{343e9a8f-c1de-11e4-b98f-806e6f6e6963}\
name     : \\?\Volume{343e9a8f-c1de-11e4-b98f-806e6f6e6963}\
capacity : 523235328

deviceid : \\?\Volume{07ec83a6-0000-0000-0000-010000000000}\
name     : C:\mountedfolder\
capacity : 1070592000

deviceid : \\?\Volume{58dafacc-c28b-11e4-95bb-3863bbba0e0f}\
name     : C:\
capacity : 253377900544

deviceid : \\?\Volume{25083962-0000-0000-0000-c01d3b000000}\
name     : D:\
capacity : 2148532224`
```

If I attempt to iterate the disks in psutil, I do not see my disk at C:\mountedfolder\

```
C:\> py
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_partitions()
[sdiskpart(device='C:\\', mountpoint='C:\\', fstype='NTFS', opts='rw,fixed'), 
 sdiskpart(device='D:\\', mountpoint='D:\\', fstype='FAT32', opts='rw,fixed')]
>>>
```

If I assign a drive letter ( like E:) to the same disk at c:\mountedfolder\ I can list it in powershell 

```
C:\>  Get-WmiObject -namespace "root/cimv2" -query "SELECT Name, Capacity, FreeSpace, deviceid FROM Win32_Volume WHERE DriveType = 3" | select deviceid,name,capacity | format-list


deviceid : \\?\Volume{343e9a8f-c1de-11e4-b98f-806e6f6e6963}\
name     : \\?\Volume{343e9a8f-c1de-11e4-b98f-806e6f6e6963}\
capacity : 523235328

deviceid : \\?\Volume{07ec83a6-0000-0000-0000-010000000000}\
name     : E:\
capacity : 1070592000

deviceid : \\?\Volume{58dafacc-c28b-11e4-95bb-3863bbba0e0f}\
name     : C:\
capacity : 253377900544

deviceid : \\?\Volume{25083962-0000-0000-0000-c01d3b000000}\
name     : D:\
capacity : 2148532224
```

Note the deviceid of E:\ matches the deviceid of C:\mountedfolder\ from the previous powershell block.

Now that the same disk is assigned E:\, I can iterate it in psutil 

```
C:\> py
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_partitions()
[sdiskpart(device='C:\\', mountpoint='C:\\', fstype='NTFS', opts='rw,fixed'), 
 sdiskpart(device='D:\\', mountpoint='D:\\', fstype='FAT32', opts='rw,fixed'), 
 sdiskpart(device='E:\\', mountpoint='E:\\', fstype='NTFS', opts='rw,fixed')]
>>> 
```

**Comment by giampaolo** [comment] 2016-02-24 08:25
I think the issue may be here: https://github.com/giampaolo/psutil/blob/ab9f29bd2689ac9623e5ac078c880c2fae7743f3/psutil/_psutil_windows.c#L2372 (skipping drives with no root dir). 
If you can compile psutil you can try to remove that `(type == DRIVE_NO_ROOT_DIR) ||` line and see if it makes any difference.
If you can't compile psutil, I should try myself: how do you mount a folder such as  C:\mountedfolder\?

**Comment by MattGirolami** [comment] 2016-02-24 20:40
Having some issues getting it to compile myself, never hacked on python so trying to get all of the prereqs figured out :smile: . 

To try it yourself on Windows, do Start -> Run -> mmc

Under File, select add/remove snapin, then add the Disk Management Snapin and connect to your local computer when prompted. 

Right click on Disk Management in the left hand pane and select 'Create VHD' . This will allow you to create a virtual hard drive. Set a size and a file location, you will get a .vhd file. You could also attach a new hard drive, usb drive, etc. instead. 

In the lower center pane you should have a new disk that is offline/not initialized. Right click on the disk and select initialize. Then, right click on box to the right that says X MB unallocated. Select new simple volume. When prompted to assign a drive letter, select the radio button for 'Mount in the following empty NTFS folder' and select any empty folder on a different drive. When prompted, format the volume as NTFS. 

You can then browse to that file path in Windows explorer. It will have a hard drive icon in Windows explorer rather than the standard folder icon. 

In the upper center pane of Disk Management you can right click on any volume to assign/unassign/change mounted folders and drive letters at any time.

**Comment by giampaolo** [comment] 2016-03-01 13:19
I forgot about `all` argument. Can you try `psutil.disk_partitions(all=True)`? That will skip the `DRIVE_NO_ROOT` check.

**Comment by jhomann** [comment] 2016-06-04 08:07
I can confirm that even with `all=True` it still does not show up. A good way to do it is mount a partition as a drive letter, say `Z:` and in the computer management window, under disk management, right click on the `Z:` drive > Change Drive Letter and Paths, then click on "Add..." which will bring up a menu to select a folder to mount the partition to. I did it with some extra space on one of my spare hard drives since it was the most reliable test.

**Comment by masci** [comment] 2016-06-13 21:07
Any update on this?

**Comment by giampaolo** [comment] 2016-06-15 22:44
@jhomann can you try removing this line and see what happens? 
https://github.com/giampaolo/psutil/blob/ab9f29bd2689ac9623e5ac078c880c2fae7743f3/psutil/_psutil_windows.c#L2372

**Comment by giampaolo** [comment] 2016-06-15 22:45
Actually nevermind, you already stated that `all=True` does not make any difference.

**Comment by jomann09** [comment] 2017-12-08 23:43
So I know this isn't done "properly" (sorry I don't really program in C) because I don't know how we would want to do the loop, but essentially I have a way to show mount points - and I restricted it to only show if `all=True` and to only check if mount points can exist.

Let me know what you think, and whether or not we can do something to refactor this.

https://github.com/jomann09/psutil/commit/988f7d48a153e9ee56582a4dc4d3c4f00a157696

**Comment by giampaolo** [comment] 2017-12-09 00:29
Nice! This is certainly desirable.
About your patch, I would use a utility function to reuse this part:

```
+                        py_tuple = Py_BuildValue(
 +                            "(ssss)",
 +                            drive_letter,
 +                            mp_path,
 +                            fs_type,  // either FAT, FAT32, NTFS, HPFS, CDFS, UDF or NWFS
 +                            opts);
 +                        if (!py_tuple)
 +                            goto error;
 +                        if (PyList_Append(py_retlist, py_tuple))
 +                            goto error;
 +                        Py_DECREF(py_tuple);
```

...which is repeated 3 times (2 by "you", 1 by "me" later). 
Also, I think it makes sense to show these mountpoints also if `all=False`. That would be in line with the Linux implementation:

```
>>> pp(psutil.disk_partitions())
[...
 sdiskpart(device='/dev/nvme0n1p4', mountpoint='/var/lib/docker/plugins', fstype='ext4', opts='rw,relatime,errors=remount-ro,data=ordered'),
 sdiskpart(device='/dev/nvme0n1p4', mountpoint='/var/lib/docker/aufs', fstype='ext4', opts='rw,relatime,errors=remount-ro,data=ordered')]
>>> 
```

A PR for this would be great.

**Comment by jomann09** [comment] 2017-12-09 01:57
Awesome thanks for the info, I will re-work it a little bit with that in mind and will make a PR soon!

Thanks for the quick response.

**Comment by giampaolo** [comment] 2017-12-12 13:19
Fixed in #1192.

**Closed by giampaolo** 2017-12-12 13:19 UTC
Labels: bug, OpSys-Windows
