### ISSUE TITLE
new stats: global open files and max files

### ISSUE THREAD

**Issue by stefanfoulis** [giampaolo/psutil#683] opened 2015-09-15 17:41 UTC
Basically what is in ``/proc/sys/fs/file-nr`` on linux.

It would also be very useful if ``psutil`` could list the limits and usage of file descriptors per user as well.

**Comment by giampaolo** [comment] 2016-01-16 21:49
Closing as a duplicate of #720

**Closed by giampaolo** 2016-01-16 21:49 UTC
