### ISSUE TITLE
[Linux] Return mapping of logical CPU ID tied to each physical CPU

### ISSUE THREAD

**Issue by tjgalvin** [giampaolo/psutil#1777] opened 2020-06-24 07:14 UTC
I am wondering whether it would be feasible to return a `dict` type objects that would be able to be used to resolve which logical CPUs are tied to a single physical core. This would be useful information if attempting to intelligently decide how many compute heavy sub-processes to spawn, which can be used in conjunction with `psutil.Process.cpu_affinity` to tie processes to certain CPUs. I specify linux in the title but I would imagine this being useful elsewhere.

**Comment by giampaolo** [comment] 2020-06-24 09:30
Mmm... this reminded me of https://github.com/giampaolo/psutil/pull/643/files, ma am not sure if it does what you ask.

**Comment by giampaolo** [comment] 2020-06-24 09:31
Mmm.. this reminded me of https://github.com/giampaolo/psutil/pull/643/

**Comment by tjgalvin** [comment] 2020-06-25 02:07
Actually, they does look pretty bang on what I was thinking. Was there ever a reason this was not pulled in? I see it is a few years ago now.

**Comment by giampaolo** [comment] 2020-06-25 02:19
Because it was a PoC. Generally speaking, before any new API gets in, it must be clear what info we can fetch from the different OSes, and based on that come up with an API which makes sense.

**Comment by tjgalvin** [comment] 2020-06-25 02:31
Understood. I must admit I am unfamiliar with how best to do this on other platforms.

**Comment by giampaolo** [comment] 2020-06-25 02:33
Well, same here. =)

**Comment by giampaolo** [comment] 2020-06-25 02:36
I'm gonna close this as duplicate of #643 which I will keep open as a reminder of a possible new feature.

**Closed by giampaolo** 2020-06-25 02:36 UTC
Labels: enhancement
