### ISSUE TITLE
list(psutil.win_service_iter()) throwing exception UnicodeDecodeError

### ISSUE THREAD

**Issue by Kozubi** [giampaolo/psutil#879] opened 2016-09-01 05:10 UTC
Hello,
My platform is:
Windows 10 pro 64 bit polish language
When I try to use 
```python
list(psutil.win_service_iter())
psutil.win_service_get("alg")
````
I get exception:
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python34\lib\site-packages\psutil\_pswindows.py", line 342, in win_service_iter
    for name, display_name in cext.winservice_enumerate():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 2: invalid start byte
```

**Comment by giampaolo** [comment] 2016-09-01 11:34
Closing as a duplicate of #866. I will release a new version soon.

**Closed by giampaolo** 2016-09-01 11:34 UTC
