### ISSUE TITLE
[Windows 10 Pro] Incorrect WiFi IP address reporting when not connected or turned off

### ISSUE THREAD

**Issue by Sighi-04** [giampaolo/psutil#2136] opened 2022-09-06 22:46 UTC
## Summary

* OS:  Windows 10 Pro 64 bit (tested and working correctly on Ubuntu 22.04 LTS)
* Architecture:  64 bit Intel X86 
* Psutil version:  5.9.2 
* Python version:  3.7.9 
* Type: core 

## Description
net_if_addrs() reports last assigned IP address for WiFi interface even when it's not connected or turned off. I'm attaching 3 screenshots in which i start from my studio wifi, move over to my phone's hotspot and then turn off wifi, checking the IP address of the WiFi NIC in every step.
#### Studio WiFi
![1  Wifi](https://user-images.githubusercontent.com/83777862/188752859-0497c0b3-06b2-43ed-aa70-5f871f628e98.png)
#### Phone Hotspot
![2  Hotspot](https://user-images.githubusercontent.com/83777862/188752877-d0e91052-aee4-4725-bde7-14fb7ade27f3.png)
#### WiFi off
![3  Turned off](https://user-images.githubusercontent.com/83777862/188752886-f3aea95a-9584-49c4-917a-5b7121c476af.png)

You can see that after turning WiFi off it still reports the last IP address (in this case the one assigned by my phone).

In case it matters, my WiFi card is an Intel WiFi 6 AX200.

**Comment by giampaolo** [comment] 2022-09-19 19:26
I think it doesn't matter whether the NIC interface is active or not. I guess IP probably remains assigned. Does `ipconfig /all` show the IP address? 
NIC / IP addresses come from [GetAdapterAddresses](https://github.com/giampaolo/psutil/blob/b88f4d839dc4d665526e91b098d018a3d796a0ac/psutil/arch/windows/net.c#L18-L48), BTW, and this function is used by `psutil.net_if_addrs()` and psutil.net_io_counters()`.

**Comment by Sighi-04** [comment] 2022-09-19 19:44
![Screenshot](https://user-images.githubusercontent.com/83777862/191101786-eff7665b-d4e3-4e8b-8cd8-53c89dc68a96.png)
ipconfig /all does say that the card is disconnected/disabled, while psutil keeps reporting the last assigned IP address. Maybe this is a problem with the Windows API?

**Comment by giampaolo** [comment] 2022-09-19 20:26
> ipconfig /all does say that the card is disconnected/disabled, while psutil keeps reporting the last assigned IP address.

`psutil.net_if_stats()` can be used to check whether an NIC is active / running or not.
What's the output of this?

```python
>>> psutil.net_if_stats()["Wi-Fi"].isup
```

**Comment by Sighi-04** [comment] 2022-09-19 21:04
It does correctly return false when wifi is disabled. So for my usecase I can use the isup property from net_if_stats() to exclude unassigned ip addresses. I imagine this wouldn't be a top priority especially for you/your team, but checking if the interface is up before returning related IP addresses would be nice. Maybe if I ever get to it I could submit a PR.

**Comment by giampaolo** [comment] 2022-09-19 21:11
Actually `psutil.net_if_addrs()` doesn't make any promise about whether the returned NICs are up.
It's debatable, but I'm more keen on considering this "not a bug". Closing.

**Closed by giampaolo** 2022-09-19 21:11 UTC
Labels: bug, windows
