### ISSUE TITLE
WinXp : Dll load failed

### ISSUE THREAD

**Issue by nsobiratel** [giampaolo/psutil#902] opened 2016-10-03 07:27 UTC
C:\Documents and Settings\autotester>python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\psutil\__init__.py", line 124, in <module>
    from . import _pswindows as _psplatform
  File "C:\Python\lib\site-packages\psutil\_pswindows.py", line 15, in <module>
    from . import _psutil_windows as cext
ImportError: DLL load failed: Не найдена указанная процедура.

also i'm find similar issue with unanswered comments https://github.com/giampaolo/psutil/issues/348

psutil 4.3.1
python 3.4.4
windows xp sp3
pip 8.1.2

latest working psutil version - 3.4.2. And i don't find information about winxp  closed support

**Comment by giampaolo** [comment] 2016-10-18 23:24
Closing as duplicate of #810

**Closed by giampaolo** 2016-10-18 23:24 UTC
