### ISSUE TITLE
Manjaro + miniconda: install fails

### ISSUE THREAD

**Issue by asosnovsky** [giampaolo/psutil#1421] opened 2019-02-20 16:35 UTC
<pre>gcc --version
gcc (GCC) 8.2.1 20181127
</pre>
<pre>g++ --version
g++ (GCC) 8.2.1 20181127
</pre>
<pre>python --version
Python 3.7.1
</pre>
<pre>conda --version
conda 4.5.12
</pre>
<pre>uname -a
Linux vapri 4.20.10-1-MANJARO #1 SMP PREEMPT Fri Feb 15 21:46:13 UTC 2019 x86_64 GNU/Linux
</pre>

The following is what happens when I run the install
<pre>pip install psutil
Collecting psutil
  Using cached https://files.pythonhosted.org/packages/c7/01/7c30b247cdc5ba29623faa5c8cf1f1bbf7e041783c340414b0ed7e067c64/psutil-5.5.1.tar.gz
Building wheels for collected packages: psutil
  Running setup.py bdist_wheel for psutil ... error
  Complete output from command /home/ari/miniconda3/bin/python -u -c &quot;import setuptools, tokenize;__file__=&apos;/tmp/pip-install-15hpcy_l/psutil/setup.py&apos;;f=getattr(tokenize, &apos;open&apos;, open)(__file__);code=f.read().replace(&apos;\r\n&apos;, &apos;\n&apos;);f.close();exec(compile(code, __file__, &apos;exec&apos;))&quot; bdist_wheel -d /tmp/pip-wheel-jyrv73vb --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/psutil
  copying psutil/_pswindows.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/_compat.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/_psosx.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/__init__.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/_common.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/_pslinux.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/_pssunos.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/_psaix.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/_psbsd.py -&gt; build/lib.linux-x86_64-3.7/psutil
  copying psutil/_psposix.py -&gt; build/lib.linux-x86_64-3.7/psutil
  creating build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_unicode.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_sunos.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_posix.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_windows.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_process.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_osx.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/__init__.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_misc.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_linux.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_system.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_connections.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_memory_leaks.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_aix.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_contracts.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/test_bsd.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  copying psutil/tests/__main__.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
  running build_ext
  building &apos;psutil._psutil_linux&apos; extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/psutil
  gcc -pthread -B /home/ari/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=551 -DPSUTIL_LINUX=1 -I/home/ari/miniconda3/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o
  gcc -pthread -B /home/ari/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=551 -DPSUTIL_LINUX=1 -I/home/ari/miniconda3/include/python3.7m -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_posix.o
  psutil/_psutil_posix.c: In function ‘psutil_net_if_flags’:
  psutil/_psutil_posix.c:415:5: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
       strncpy(ifr.ifr_name, nic_name, sizeof(ifr.ifr_name));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  psutil/_psutil_posix.c: In function ‘psutil_net_if_mtu’:
  psutil/_psutil_posix.c:376:5: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
       strncpy(ifr.ifr_name, nic_name, sizeof(ifr.ifr_name));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  gcc -pthread -B /home/ari/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=551 -DPSUTIL_LINUX=1 -I/home/ari/miniconda3/include/python3.7m -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_linux.o
  psutil/_psutil_linux.c: In function ‘psutil_net_if_duplex_speed’:
  psutil/_psutil_linux.c:539:5: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
       strncpy(ifr.ifr_name, nic_name, sizeof(ifr.ifr_name));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  gcc -pthread -shared -B /home/ari/miniconda3/compiler_compat -L/home/ari/miniconda3/lib -Wl,-rpath=/home/ari/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/psutil/_psutil_common.o build/temp.linux-x86_64-3.7/psutil/_psutil_posix.o build/temp.linux-x86_64-3.7/psutil/_psutil_linux.o -o build/lib.linux-x86_64-3.7/psutil/_psutil_linux.cpython-37m-x86_64-linux-gnu.so
  /home/ari/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: unable to initialize decompress status for section .debug_info
  /home/ari/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: unable to initialize decompress status for section .debug_info
  /home/ari/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: unable to initialize decompress status for section .debug_info
  /home/ari/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: unable to initialize decompress status for section .debug_info
  build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: file not recognized: file format not recognized
  collect2: error: ld returned 1 exit status
  error: command &apos;gcc&apos; failed with exit status 1
  
  ----------------------------------------
<font color="#D54646">  Failed building wheel for psutil</font>
  Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil
  Running setup.py install for psutil ... error
    Complete output from command /home/ari/miniconda3/bin/python -u -c &quot;import setuptools, tokenize;__file__=&apos;/tmp/pip-install-15hpcy_l/psutil/setup.py&apos;;f=getattr(tokenize, &apos;open&apos;, open)(__file__);code=f.read().replace(&apos;\r\n&apos;, &apos;\n&apos;);f.close();exec(compile(code, __file__, &apos;exec&apos;))&quot; install --record /tmp/pip-record-9iqaiw6j/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pswindows.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/_compat.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psosx.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/__init__.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/_common.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pslinux.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/_pssunos.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psaix.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psbsd.py -&gt; build/lib.linux-x86_64-3.7/psutil
    copying psutil/_psposix.py -&gt; build/lib.linux-x86_64-3.7/psutil
    creating build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_unicode.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_sunos.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_posix.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_windows.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_process.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_osx.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/__init__.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_misc.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_linux.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_system.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_connections.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_aix.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_contracts.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/test_bsd.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    copying psutil/tests/__main__.py -&gt; build/lib.linux-x86_64-3.7/psutil/tests
    running build_ext
    building &apos;psutil._psutil_linux&apos; extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/psutil
    gcc -pthread -B /home/ari/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=551 -DPSUTIL_LINUX=1 -I/home/ari/miniconda3/include/python3.7m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_common.o
    gcc -pthread -B /home/ari/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=551 -DPSUTIL_LINUX=1 -I/home/ari/miniconda3/include/python3.7m -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_posix.o
    psutil/_psutil_posix.c: In function ‘psutil_net_if_flags’:
    psutil/_psutil_posix.c:415:5: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
         strncpy(ifr.ifr_name, nic_name, sizeof(ifr.ifr_name));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    psutil/_psutil_posix.c: In function ‘psutil_net_if_mtu’:
    psutil/_psutil_posix.c:376:5: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
         strncpy(ifr.ifr_name, nic_name, sizeof(ifr.ifr_name));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    gcc -pthread -B /home/ari/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=551 -DPSUTIL_LINUX=1 -I/home/ari/miniconda3/include/python3.7m -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-3.7/psutil/_psutil_linux.o
    psutil/_psutil_linux.c: In function ‘psutil_net_if_duplex_speed’:
    psutil/_psutil_linux.c:539:5: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
         strncpy(ifr.ifr_name, nic_name, sizeof(ifr.ifr_name));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    gcc -pthread -shared -B /home/ari/miniconda3/compiler_compat -L/home/ari/miniconda3/lib -Wl,-rpath=/home/ari/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/psutil/_psutil_common.o build/temp.linux-x86_64-3.7/psutil/_psutil_posix.o build/temp.linux-x86_64-3.7/psutil/_psutil_linux.o -o build/lib.linux-x86_64-3.7/psutil/_psutil_linux.cpython-37m-x86_64-linux-gnu.so
    /home/ari/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: unable to initialize decompress status for section .debug_info
    /home/ari/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: unable to initialize decompress status for section .debug_info
    /home/ari/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: unable to initialize decompress status for section .debug_info
    /home/ari/miniconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: unable to initialize decompress status for section .debug_info
    build/temp.linux-x86_64-3.7/psutil/_psutil_common.o: file not recognized: file format not recognized
    collect2: error: ld returned 1 exit status
    error: command &apos;gcc&apos; failed with exit status 1
    
    ----------------------------------------
<font color="#D54646">Command &quot;/home/ari/miniconda3/bin/python -u -c &quot;import setuptools, tokenize;__file__=&apos;/tmp/pip-install-15hpcy_l/psutil/setup.py&apos;;f=getattr(tokenize, &apos;open&apos;, open)(__file__);code=f.read().replace(&apos;\r\n&apos;, &apos;\n&apos;);f.close();exec(compile(code, __file__, &apos;exec&apos;))&quot; install --record /tmp/pip-record-9iqaiw6j/install-record.txt --single-version-externally-managed --compile&quot; failed with error code 1 in /tmp/pip-install-15hpcy_l/psutil/</font>
</pre>

**Comment by giampaolo** [comment] 2019-02-25 16:55
I don't have this platform to test against so I'm afraid you're on your own. :-\

**Comment by giampaolo** [comment] 2020-12-29 01:14
Duplicate of https://github.com/giampaolo/psutil/issues/1482.

**Closed by giampaolo** 2020-12-29 01:14 UTC
Labels: bug
