### ISSUE TITLE
add function to get the default route

### ISSUE THREAD

**Issue by nzjrs** [giampaolo/psutil#716] opened 2015-12-10 21:20 UTC
a wrapper around the command ```ip route```

**Comment by giampaolo** [comment] 2015-12-12 11:24
Are you interested in the default gateway?

**Comment by nzjrs** [comment] 2015-12-12 11:36
I'm actually interested in the device from which default traffic will be
routed

default via 192.168.0.1 dev eth1  proto static

**Comment by giampaolo** [comment] 2015-12-14 18:01
Closing as duplicate of https://github.com/giampaolo/psutil/issues/667. In the meantime you might want to take a look at netifaces lib which provides info about the gateways: https://pypi.python.org/pypi/netifaces

**Closed by giampaolo** 2015-12-14 18:01 UTC

**Comment by nzjrs** [comment] 2015-12-14 18:16
Is it really a dupe if I want the device and not the IP?

**Comment by giampaolo** [comment] 2015-12-14 18:19
Please try to describe what you would expect in terms of API.
netifaces do this:

```
>>> import netifaces
>>> netifaces.gateways()
{2: [('10.0.1.1', 'en0', True), ('10.2.1.1', 'en1', False)], 30: [('fe80::1', 'en0', True)], 'default': { 2: ('10.0.1.1', 'en0'), 30: ('fe80::1', 'en0') }}
```

...on my machine:

```
>>> netifaces.gateways()
{'default': {2: ('10.0.0.1', 'wlan0')}, 2: [('10.0.0.1', 'wlan0', True)]}
>>> 
```

I'm asking this because it is not entirely clear to me how network gateways work.

**Comment by ofirule** [comment] 2023-11-26 14:22
It's really missing.
Reading all routes which may include static routes, and not only the interface gw is very usefull
