### ISSUE TITLE
`install_requires` fails as of 3.2.1

### ISSUE THREAD

**Issue by meunierd** [giampaolo/psutil#695] opened 2015-10-02 14:43 UTC
If I `pip install psutil==3.2.1` everything is fine but if I have a project with psutil in its setup function's install_requires, it will fail with the following traceback:

```
Downloading https://pypi.python.org/packages/source/p/psutil/psutil-3.2.1.tar.gz#md5=a308816e735021fd4bf6aa561725c1aa
Processing psutil-3.2.1.tar.gz
Writing /tmp/easy_install-6w0fdk38/psutil-3.2.1/setup.cfg
Running psutil-3.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6w0fdk38/psutil-3.2.1/egg-dist-tmp-m59m7k4l
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    test_suite='nose.collector',
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/core.py", line 149, in setup
    dist.run_commands()
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/command/develop.py", line 27, in run
    self.install_for_development()
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/command/develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 671, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/pkg_resources.py", line 564, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/pkg_resources.py", line 802, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/pkg_resources.py", line 814, in obtain
    return installer(requirement)
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 593, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 623, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 809, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1015, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1000, in run_setup
    run_setup(setup_script, args)
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "/home/ubuntu/virtualenvs/venv-3.4.0/lib/python3.4/site-packages/setuptools/compat.py", line 78, in execfile
    exec(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 162, in <module>
  File "setup.py", line 156, in get_ethtool_macro
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/ccompiler.py", line 566, in compile
    depends, extra_postargs)
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/ccompiler.py", line 348, in _setup_compile
    self.mkpath(os.path.dirname(obj))
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/ccompiler.py", line 915, in mkpath
    mkpath(name, mode, dry_run=self.dry_run)
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/dir_util.py", line 66, in mkpath
    log.info("creating %s", head)
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/log.py", line 44, in info
    self._log(INFO, msg, args)
  File "/home/ubuntu/.pyenv/versions/3.4.0/lib/python3.4/distutils/log.py", line 30, in _log
    if stream.errors == 'strict':
AttributeError: 'DummyFile' object has no attribute 'errors'
```

**Comment by giampaolo** [comment] 2015-10-04 16:49
Closing as a duplicate of #678.
I just released psutil 3.2.2 and this is supposed to be fixed.

**Closed by giampaolo** 2015-10-04 16:49 UTC
