### ISSUE TITLE
Unable to install due to `error: unknown type name '__darwin_wctype_t'`

### ISSUE THREAD

**Issue by Nithanaroy** [giampaolo/psutil#1336] opened 2018-09-15 22:17 UTC
`pip install psutil` fails with **error: unknown type name '__darwin_wctype_t'**. `conda install psutil` works though. More details on how I arrived at this error at https://github.com/ray-project/ray/issues/2890#issue-360578427 - including environment details, stack trace etc. How do I install `psutil` in non-conda environments?

**Comment by giampaolo** [comment] 2019-02-26 23:45
duplicate of https://github.com/giampaolo/psutil/issues/1399

**Closed by giampaolo** 2019-02-26 23:45 UTC
