### ISSUE TITLE
Command line with ':' in name break command line parsing

### ISSUE THREAD

**Issue by tgermain** [giampaolo/psutil#980] opened 2017-02-21 10:59 UTC
Hi,

# Use case
I'm trying to check if nginx is running using `psutil.process_iter()` using something like : 
```python
import psutil

for process in psutil.process_iter():
    if process.cmd_line()[0] == "nginx":
       return true
else:
    return false
```

I'm running this on debian 8,
```
# uname -a
Linux admin-1 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
# pip freeze | grep psutil
psutil==5.1.3
```

# How to reproduce 

Install and run nginx 
here is the command line of nginx as reported by `ps aux | grep nginx` :
`nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf`

# What I expect
```python
# assuming process is my nginx process
>>>> process.cmd_line()
['nginx:', 'master', 'process', '/usr/sbin/nginx', '-c', '/etc/nginx/nginx.conf']

```
I don't know if it should be `nginx:` or `nginx` for the first part.

# What I get
```python
# assuming process is my nginx process
>>>> process.cmd_line()
['nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf']

```

It seems that the comma in the command line break the parsing, splitting of the command line. 

I can cope with this for now by using `process.name()` instead of `process.cmd_line()[0]`.

**Comment by ivdunin** [comment] 2017-02-21 16:12
Hi!

You should check /proc/<nginx_pid>/cmdline file.
Delimiter for cmdline is \x00.

For example, I did this on my machine:

This is what I got from psutil.
`['nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf']`

This is hexdump of this cmdline file.
`hexdump /proc/14272/cmdline`
`0000000 676e 6e69 3a78 6d20 7361 6574 2072 7270`
`0000010 636f 7365 2073 752f 7273 732f 6962 2f6e`
`0000020 676e 6e69 2078 632d 2f20 7465 2f63 676e`
`0000030 6e69 2f78 676e 6e69 2e78 6f63 666e     `
`000003e`

As you can see, there is no delimiter to split command line. So, it is correct behavior of cmdline function.

Using this code for checking process name:
`process.cmd_line()[0] == "nginx"`
Isn't good idea.

**Comment by giampaolo** [comment] 2017-03-24 11:57
I installed nginx and reproduced the described scenario. I'm not sure why nginx produces such kind of cmdline but psutil is right in what it is returning. Since there is not `\x00` delimiter the cmdline is not split. I don't see any way to reliably split the cmdline otherwise. I'll just close this one as "won't fix".

**Closed by giampaolo** 2017-03-24 11:57 UTC
