### ISSUE TITLE
[Windows] /proc/meminfo parsing breaks nondeterministically on WSL

### ISSUE THREAD

**Issue by mehrdadn** [giampaolo/psutil#1666] opened 2020-01-17 22:20 UTC
**Platform**
* Windows 10.0.18363.535
* psutil 5.6.3

**Bug description**
WSL has an issue where it occasionally omits a space after colons in `/proc/meminfo` (this happens to me for `SwapFree:`). This crashes psutil when a function like `virtual_memory` is called.

Example stack trace:

    lib/python3.7/site-packages/psutil/__init__.py:2089: in virtual_memory
    ret = _psplatform.virtual_memory()
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
        def virtual_memory():
            ...
            missing_fields = []
            mems = {}
            with open_binary('%s/meminfo' % get_procfs_path()) as f:
                for line in f:
                    fields = line.split()
    >               mems[fields[0]] = int(fields[1]) * 1024
    
    ValueError: invalid literal for int() with base 10: b'kB'

I have no repro for this; it either happens when you call `virtual_memory` or it doesn't. Sometimes it is consistently breaking, sometimes it is consistently successful.

Note that `virtual_memory` is just one example. I believe the parsing a problem throughout the codebase. One way to potentially fix this is to look for the colon and then split on spaces for subsequent fields. For example, in this case, that might result in:

    name, cols = line.split(':', 1)
    fields = cols[0].lstrip().split()

However, there are other places in the code where this problem occurs too; this is not the only location.

**Comment by giampaolo** [comment] 2020-01-17 23:30
Windows implementation does not rely on  /proc/meminfo (Linux does). Is this bash on Windows or something?

**Comment by mehrdadn** [comment] 2020-01-17 23:32
This is for WSL which is the [Linux subsystem on Windows](https://docs.microsoft.com/en-us/windows/wsl/faq).

**Comment by giampaolo** [comment] 2020-01-17 23:50
Oh that. Never played with it. Except for this issue, does psutil work out of the box?

**Comment by mehrdadn** [comment] 2020-01-17 23:55
I haven't used `psutil` on WSL much to be honest, so I'm not sure. I think many parts do work, but many tests don't pass, so I assume some parts I don't know about are probably broken.

By the way, if by "Bash on Windows" you meant the thing Microsoft released in 2016, we're talking about the same thing. :-) They just call it WSL now. Originally I assumed you were talking about the Bash on Windows from MSYS2, which is an unrelated thing (Cygwin fork).

**Comment by giampaolo** [comment] 2020-01-18 00:03
Could you paste the test output? (`python -m psutil.tests` will do)

> By the way, if by "Bash on Windows" you meant the thing Microsoft released in 2016, we're talking about the same thing. :-) They just call it WSL now. 

Oh OK. I heard rumors about this but never tried. I guess that means Cygwin will gradually be much less used.

**Comment by mehrdadn** [comment] 2020-01-18 00:09
Sure, here you go. Note that I can't run all the tests because the last one I see gets stuck (spikes my CPU to 100%).

> I guess that means Cygwin will gradually be much less used.

Somewhat, yeah. Probably moreso for Cygwin than MSYS2. I do run into situations where MSYS2 is more appropriate (or even the only option), so at least that one is probably going to stick around for a while.

```
psutil.tests.test_aix.AIXSpecificTestCase.test_cpu_count_logical ... skipped: AIX only
psutil.tests.test_aix.AIXSpecificTestCase.test_cpu_stats ... skipped: AIX only
psutil.tests.test_aix.AIXSpecificTestCase.test_net_if_addrs_names ... skipped: AIX only
psutil.tests.test_aix.AIXSpecificTestCase.test_swap_memory ... skipped: AIX only
psutil.tests.test_aix.AIXSpecificTestCase.test_virtual_memory ... skipped: AIX only
psutil.tests.test_bsd.BSDSpecificTestCase.test_cpu_count_logical ... skipped: BSD only
psutil.tests.test_bsd.BSDSpecificTestCase.test_disks ... skipped: BSD only
psutil.tests.test_bsd.BSDSpecificTestCase.test_net_if_stats ... skipped: BSD only
psutil.tests.test_bsd.BSDSpecificTestCase.test_process_create_time ... skipped: BSD only
psutil.tests.test_bsd.BSDSpecificTestCase.test_virtual_memory_total ... skipped: BSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_boot_time ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_cpu_frequency_against_sysctl ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_cpu_stats_ctx_switches ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_cpu_stats_interrupts ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_cpu_stats_soft_interrupts ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_cpu_stats_syscalls ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_muse_vmem_active ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_muse_vmem_buffers ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_muse_vmem_cached ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_muse_vmem_free ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_muse_vmem_inactive ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_muse_vmem_total ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_muse_vmem_wired ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_proc_cmdline ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_proc_cpu_times ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_proc_ctx_switches ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_proc_exe ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_proc_memory_maps ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_proc_uids_gids ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_sensors_battery ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_sensors_battery_against_sysctl ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_sensors_battery_no_battery ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_sensors_temperatures_against_sysctl ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_swapmem_free ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_swapmem_total ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_swapmem_used ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_vmem_active ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_vmem_buffers ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_vmem_cached ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_vmem_free ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_vmem_inactive ... skipped: FREEBSD only
psutil.tests.test_bsd.FreeBSDSpecificTestCase.test_vmem_wired ... skipped: FREEBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_cpu_stats_ctx_switches ... skipped: NETBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_cpu_stats_interrupts ... skipped: NETBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_swapmem_free ... skipped: NETBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_swapmem_total ... skipped: NETBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_swapmem_used ... skipped: NETBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_vmem_buffers ... skipped: NETBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_vmem_free ... skipped: NETBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_vmem_shared ... skipped: NETBSD only
psutil.tests.test_bsd.NetBSDSpecificTestCase.test_vmem_total ... skipped: NETBSD only
psutil.tests.test_bsd.OpenBSDSpecificTestCase.test_boot_time ... skipped: OPENBSD only
psutil.tests.test_connections.TestConnectedSocketPairs.test_combos ... FAIL
psutil.tests.test_connections.TestConnectedSocketPairs.test_multi_sockets_filtering ... ERROR
psutil.tests.test_connections.TestConnectedSocketPairs.test_tcp ... FAIL
psutil.tests.test_connections.TestConnectedSocketPairs.test_unix ... ERROR
psutil.tests.test_connections.TestMisc.test_connection_constants ... OK
psutil.tests.test_connections.TestSystemWideConnections.test_it ... ERROR
psutil.tests.test_connections.TestSystemWideConnections.test_multi_sockets_procs ... ERROR
psutil.tests.test_connections.TestSystemWideConnections.test_multi_socks ... ERROR
psutil.tests.test_connections.TestUnconnectedSockets.test_tcp_v4 ... ERROR
psutil.tests.test_connections.TestUnconnectedSockets.test_tcp_v6 ... ERROR
psutil.tests.test_connections.TestUnconnectedSockets.test_udp_v4 ... ERROR
psutil.tests.test_connections.TestUnconnectedSockets.test_udp_v6 ... ERROR
psutil.tests.test_connections.TestUnconnectedSockets.test_unix_tcp ... ERROR
psutil.tests.test_connections.TestUnconnectedSockets.test_unix_udp ... ERROR
psutil.tests.test_contracts.TestAvailability.test_PROCFS_PATH ... OK
psutil.tests.test_contracts.TestAvailability.test_battery ... OK
psutil.tests.test_contracts.TestAvailability.test_cpu_affinity ... OK
psutil.tests.test_contracts.TestAvailability.test_cpu_freq ... OK
psutil.tests.test_contracts.TestAvailability.test_linux_ioprio ... OK
psutil.tests.test_contracts.TestAvailability.test_linux_rlimit ... FAIL
psutil.tests.test_contracts.TestAvailability.test_proc_cpu_affinity ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_cpu_num ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_environ ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_gids ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_io_counters ... FAIL
psutil.tests.test_contracts.TestAvailability.test_proc_ionice ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_memory_maps ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_num_fds ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_num_handles ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_rlimit ... FAIL
psutil.tests.test_contracts.TestAvailability.test_proc_terminal ... OK
psutil.tests.test_contracts.TestAvailability.test_proc_uids ... OK
psutil.tests.test_contracts.TestAvailability.test_sensors_fans ... OK
psutil.tests.test_contracts.TestAvailability.test_sensors_temperatures ... OK
psutil.tests.test_contracts.TestAvailability.test_win_priority ... OK
psutil.tests.test_contracts.TestAvailability.test_win_service ... OK
psutil.tests.test_contracts.TestDeprecations.test_memory_info_ex ... ERROR
psutil.tests.test_contracts.TestFetchAllProcesses.test_fetch_all ... ERROR
psutil.tests.test_contracts.TestSystem.test_cpu_times ... OK
psutil.tests.test_contracts.TestSystem.test_disk_partitions ... OK
psutil.tests.test_contracts.TestSystem.test_io_counters ... OK
psutil.tests.test_contracts.TestSystem.test_net_connections ... ERROR
psutil.tests.test_contracts.TestSystem.test_net_if_addrs ... OK
psutil.tests.test_contracts.TestSystem.test_net_if_stats ... OK
psutil.tests.test_contracts.TestSystem.test_net_io_counters ... OK
psutil.tests.test_contracts.TestSystem.test_sensors_fans ... OK
psutil.tests.test_contracts.TestSystem.test_sensors_temperatures ... OK
psutil.tests.test_contracts.TestSystem.test_users ... OK
psutil.tests.test_linux.TestLoadAvg.test_getloadavg ... OK
psutil.tests.test_linux.TestMisc.test_boot_time ... ERROR
psutil.tests.test_linux.TestMisc.test_boot_time_mocked ... OK
psutil.tests.test_linux.TestMisc.test_cpu_steal_decrease ... OK
psutil.tests.test_linux.TestMisc.test_issue_687 ... ERROR
psutil.tests.test_linux.TestMisc.test_no_procfs_on_import ... OK
psutil.tests.test_linux.TestMisc.test_pid_exists_no_proc_status ... OK
psutil.tests.test_linux.TestMisc.test_procfs_path ... OK
psutil.tests.test_linux.TestMisc.test_users_mocked ... OK
psutil.tests.test_linux.TestProcess.test_cmdline_mocked ... OK
psutil.tests.test_linux.TestProcess.test_cmdline_spaces_mocked ... OK
psutil.tests.test_linux.TestProcess.test_cwd_zombie ... OK
psutil.tests.test_linux.TestProcess.test_exe_mocked ... OK
psutil.tests.test_linux.TestProcess.test_issue_1014 ... OK
psutil.tests.test_linux.TestProcess.test_memory_full_info ... ERROR
psutil.tests.test_linux.TestProcess.test_memory_full_info_mocked ... OK
psutil.tests.test_linux.TestProcess.test_open_files_fd_gone ... FAIL
psutil.tests.test_linux.TestProcess.test_open_files_file_gone ... FAIL
psutil.tests.test_linux.TestProcess.test_open_files_mode ...
```

**Comment by giampaolo** [comment] 2020-01-18 02:30
As I suspected, judging from those few tests WSL is basically a new platform. It looks so similar to Linux that psutil compiles/builds out of the box (I'm surprised it does actually), but there are enough differences (in `/proc` filesystem, and others for sure) to deserve its own implementation.

**Comment by mehrdadn** [comment] 2020-01-18 03:40
Funny enough I'm actually surprised this many tests fail, I would've expected most to pass since WSL is supposed to provide a Linux environment to userspace.  

I'm not sure how many of them are deeper issues vs. parsing glitches like this one, but I can probably run more tests after these parsing issues are fixed.

**Comment by giampaolo** [comment] 2020-01-20 12:18
Closing as duplicate of #1251.

**Closed by giampaolo** 2020-01-20 12:18 UTC
Labels: bug
