### ISSUE TITLE
Uses incorrect dll

### ISSUE THREAD

**Issue by kdschlosser** [giampaolo/psutil#947] opened 2016-12-29 16:12 UTC
I am not sure how psutil gets the path to python27.dll But i am running it from inside of a piece of software that uses python 2.6 I do have python 2.7 installed and have removed any path statements pointing to it. but it is still trying to use that file instead of the one that is used in the piece of software.

```
   Traceback (most recent call last):
     Python script "0", line 1, in <module>
       import psutil
     File "C:\Program Files (x86)\EventGhost2\lib26\site-packages\psutil\__init__.py", line 126, in <module>
       from . import _pswindows as _psplatform
     File "C:\Program Files (x86)\EventGhost2\lib26\site-packages\psutil\_pswindows.py", line 16, in <module>
       from . import _psutil_windows as cext
   ImportError: Module use of python27.dll conflicts with this version of Python.
```

**Comment by giampaolo** [comment] 2016-12-29 16:42
Well, I really have no idea and it is the first time I see that kind of error message. It looks like this is something related to your system PATH rather than psutil itself.

**Comment by kdschlosser** [comment] 2016-12-29 19:48
that's what i thought, so i removed all python entries in the system path. and it still comes up.

the strange thing is if i use an older version of psutil no problems. specifically 3.3

**Comment by giampaolo** [comment] 2017-01-09 15:54
If you git clone the psutil repository you can try the `make uninstall` command.
That tries hard to uninstall any installed psutil version (via pip).
For the time being, I'm going to close this one as it looks it's not a bug with psutil.

**Closed by giampaolo** 2017-01-09 15:54 UTC
