### ISSUE TITLE
Packaged wheels/exes are not compatible with Win XP

### ISSUE THREAD

**Issue by bitranox** [giampaolo/psutil#811] opened 2016-04-28 16:01 UTC
can not load psutil 4.1.0 on Windows XP, SP3, Python 3.4.3 :

Microsoft Windows XP [Version 5.1.2600]
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32

import psutil
Traceback (most recent call last):
File "", line 1, in 
File "C:\Python34\lib\site-packages\psutil__init__.py", line 124, in
from . import _pswindows as _psplatform
File "C:\Python34\lib\site-packages\psutil_pswindows.py", line 14, in 
from . import _psutil_windows as cext
ImportError: DLL load failed: The specified procedure could not be found.

And I can not update that particular machine, because it is a gateway for an ancient database.
Please Help !

**Comment by giampaolo** [comment] 2016-05-31 22:24
This is likely due to the old pip version you're using. `pip install -U pip` should fix this issue.

**Comment by giampaolo** [comment] 2016-05-31 22:25
Also, closing this as a duplicate of #810.

**Comment by robodude666** [comment] 2016-06-07 01:05
@giampaolo This is actually due to the fact that the psutil whls deployed to pypi are built on Windows Vista or newer (or it seems that way).

The `setup.py` script sets `_WIN32_WINNT` based on the result of `sys.getwindowsversion()` which returns the host OS version, not the target OS. Windows XP does not have the `GetTickCount64` API, which was added in Vista. This causes the above crash on `import psutil`.

Currently, the only way to get psutil to work on Windows XP is to install from source. This can be done with `pip install psutil --no-binary :all:` which will force pip to download the source and run setup.py manually.

However... that requires you to run on Windows XP. If you want to compile on Windows Vista or newer, and be able to run your python application on Windows XP you can't unless you manually modify the setup.py script before installing on your Vista or newer box.

I recommend not having the setup.py file compile based on the host OS, but instead on an extra parameter, like `pip install psutil[winxp]` or `psutil[win32]` and have a lookup table of `_WIN32_WINNT` [values](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383745(v=vs.85).aspx#macros_for_conditional_declarations) values.

-robodude666

**Comment by JokerQyou** [comment] 2016-06-07 04:13
I think @robodude666 is right. `pip install psutil` is broken on Windows XP, even with the latest pip (which is `8.1.2` currently).

**Comment by JokerQyou** [comment] 2016-06-07 04:39
**Update**

After trying different history version from pypi, `psutil==3.4.2` seems to be the last version unaffected by this issue. All versions of psutil can be installed on Windows XP, but newer version will not work.

**Comment by robodude666** [comment] 2016-06-07 05:15
Yup. Windows XP support from whl was broken with `psutil==4.0.0` because of bug fix #761.

3.4.2 was the last version that used `GetTickCount` for all versions of windows.

**Comment by aajtodd** [comment] 2016-07-05 17:24
Seeing this as well. I believe @robodude666 is correct. The logic in ab9f29b checks `_WIN32_WINNT` to see if `GetTickCount64` can be used but that only works if the host OS matches the target when building.

**Comment by giampaolo** [comment] 2016-07-05 23:55
Sorry for delaying on this one, I've been busy. As a recap: 
* the problem (breakage of compatibility with WinXP) was introduced in #761 
* because the exe/wheel files are produced with a more recent Windows version (>= Vista) where `GetTickCount64` is available, also the resulting exes/wheels are compiled with such an assumption in place, hence Win XP is unable to use those public exe/wheels
* Win XP is still compatible if psutil is compiled / installed from source, meaning this issue is with the distribution of exe/wheel files only
* 3.4.2 is the last psutil version where the distributed exe/wheel files were compatible

**Comment by giampaolo** [comment] 2016-07-06 00:13
So, as for how to fix this issue: my first idea was to not rely on the C pre-processor (`#if (_WIN32_WINNT >= 0x0600`) as we do now, and instead use a Windows API which returns the Windows version at runtime, like: 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724429(v=vs.85).aspx
...but C doesn't work like that. We need something to dynamically load the DLL at runtime so that "GetTickCount64" is defined in the C code as a string, not an actual function.
I believe something like this would help:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx

**Comment by giampaolo** [comment] 2016-07-06 00:14
...and in fact here it is (Python source code comes to help :P):
http://code.metager.de/source/xref/python/stackless/Python/pytime.c#135

**Comment by giampaolo** [comment] 2016-07-06 01:07
I submitted a patch in https://github.com/giampaolo/psutil/commit/e481df9568640fcd5ddb98742ad37b9f26e56177.
I am also attaching an exe installed which was produced on Windows 10. Can somebody try it and tell me if it can be installed on Windows XP?
[psutil-4.3.0.win32-py2.7.zip](https://github.com/giampaolo/psutil/files/348894/psutil-4.3.0.win32-py2.7.zip)

**Comment by aajtodd** [comment] 2016-07-08 17:56
I tried the build it still fails with the same DLL error.

Glancing over the code again, off the top of my head I would guess any use of `_WIN32_WINNT` at compile time may cause similar behavior (e.g. https://github.com/giampaolo/psutil/blob/e481df9568640fcd5ddb98742ad37b9f26e56177/psutil/_psutil_windows.c#L21).

**Comment by giampaolo** [comment] 2016-07-08 22:20
Mmm, you're right. In this case I'm not sure how to apply the same strategy against the .h file. I suppose C won't allow that. That leaves us with one option only: providing exes/wheels specific for Win XP, but I'm not willing to do that: it's too much effort.

**Comment by giampaolo** [comment] 2016-11-08 18:13
I'm not willing to fix this issue for new versions by distributing XP only exes/wheels but I want to provide a more meaningful error message. Something along the lines of "Windows XP is no longer supported; latest version supporting it is 3.4.2"
I would like to do this on installation via pip, but I'm not sure how (I asked here http://stackoverflow.com/questions/40492799/wheels-return-error-if-windows-xp). 
Alternatively we'll have to do this at import time.

**Comment by wiggin15** [comment] 2017-03-09 10:45
FWIW I don't think there's a problem with the #include that is wrapped with the ifdef (https://github.com/giampaolo/psutil/blob/e481df9568640fcd5ddb98742ad37b9f26e56177/psutil/_psutil_windows.c#L21) since this can't cause linking errors at runtime. Only functions that will be in the import section of the produced DLL can cause the "DLL load failed error", e.g. the use of "GetIfEntry2" (https://github.com/giampaolo/psutil/blob/e481df9568640fcd5ddb98742ad37b9f26e56177/psutil/_psutil_windows.c#L2227) - which can be bypassed the same way as GetTickCount64.

However, even if the DLL will load correctly after fixing these calls, there could still be invalid memory access (=crashes) on older systems due to incorrect struct sizes in other places where we use extended classes (e.g. https://github.com/giampaolo/psutil/blob/e481df9568640fcd5ddb98742ad37b9f26e56177/psutil/_psutil_windows.c#L741). These places can also be fixed by determining the Window version at runtime, if we want to do all this work.

In any case, the #include is only for compile time so it will not be a problem as long as we avoid using its definitions on XP. Just my two cents.

**Comment by giampaolo** [comment] 2017-03-09 11:25
Right now the doc states that latest wheel / exe version compatible with Win XP is psutil 3.4.2.
It also states that it is possible to use latest version by compiling, although it's not guaranteed it will be fully working.

**Comment by wiggin15** [comment] 2017-03-09 12:27
I understand, I'm just pointing out that theoretically it is possible to support WinXP in the same distribution - the header issue (pointed out in  https://github.com/giampaolo/psutil/issues/811#issuecomment-231486447) is not a problem.

**Comment by raphael-santos** [comment] 2017-08-08 17:48
Hi @giampaolo, that same error also happens on Windows Server 2003 R2 x64.

However we are using Python 2.7 with psutil 4.4.2. In this case, the exception is:
> Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "psutil\__init__.py", line 124, in <module>
>     from . import _pswindows as _psplatform
>   File "psutil\_pswindows.py", line 15, in <module>
>     from . import _psutil_windows as cext
> **ImportError: DLL load failed: The specified procedure could not be found.**

We've tried to updage psutil to version 5.2.2. The exception changed:

> Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "psutil\__init__.py", line 126, in <module>
>     from . import _pswindows as _psplatform
>   File "psutil\_pswindows.py", line 30, in <module>
>     raise RuntimeError(msg)
> **RuntimeError: this Windows version is too old (< Windows Vista); psutil 3.4.2 is the latest version which  supports Windows 2000, XP and 2003 server**



The only way to use psutil on Windows 2003 Server is with version 3.4.2? Is there a workaround using latest versions?

Thanks

**Comment by robodude666** [comment] 2017-08-09 17:25
@raphael-santos See my response above.

You can manually install `psutil` from source using `pip install psutil --no-binary :all:` on the target system to compile for the correct Windows version.

**Comment by RicardoNoguerales** [comment] 2018-03-03 23:16
( Using Windows XP )

`pip` keeps getting uncompatible binary package

Recently updated **Spyder** with 

`pip install --upgrade spyder`

This upgraded dependencies too, including psutil, got **psutil-5.4.3-cp27-none-win32.whl**
( binary not compatible with XP )

Spyder crashed silently during load ( no traceback, pythonw ) ... no clue
Later found a log file with the traceback, uninstalled psutil-5.4.3 , installed 3.4.2 , worked.

And today found this page, updated to 5.4.3 source, worked.

I don't have knowledge about **pip** and **Pypi** internals, but wonder if there are no means to avoid this behaviour through some package metadata, so that pip is aware it's running in XP and falls back to  download binary  3.4.2 or source  5.4.3 ?

**Comment by giampaolo** [comment] 2018-03-04 17:54
Windows XP is no longer supported. Latest version supporting it should be 3.4.2. You may try compileing 5.3.3 from sources and it may work (but not sure):
http://psutil.readthedocs.io/en/latest/#faqs

**Closed by giampaolo** 2018-03-04 17:54 UTC
